
package com.sportmaster.wc.interfaces.webservices.bombean;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.lcs.wc.util.LCSProperties;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BomEndpointService", targetNamespace = "http://www.sportmaster.ru/plmbom", wsdlLocation = "file:/C:/Users/24926/Desktop/WSDL/PlmBOM/PlmBOM.wsdl")
public class BomEndpointService
    extends Service
{

    private final static URL BOMENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException BOMENDPOINTSERVICE_EXCEPTION;
    private final static QName BOMENDPOINTSERVICE_QNAME = new QName("http://www.sportmaster.ru/plmbom", "BomEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
           // url = new URL("file:/C:/Users/24926/Desktop/WSDL/PlmBOM/PlmBOM.wsdl");
            url = new URL(LCSProperties.get("com.sportmaster.wc.interfaces.webservices.outbound.bomIntegration.bomoutboundWSDLLocation"));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOMENDPOINTSERVICE_WSDL_LOCATION = url;
        BOMENDPOINTSERVICE_EXCEPTION = e;
    }

    public BomEndpointService() {
        super(__getWsdlLocation(), BOMENDPOINTSERVICE_QNAME);
    }

    public BomEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOMENDPOINTSERVICE_QNAME, features);
    }

    public BomEndpointService(URL wsdlLocation) {
        super(wsdlLocation, BOMENDPOINTSERVICE_QNAME);
    }

    public BomEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOMENDPOINTSERVICE_QNAME, features);
    }

    public BomEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BomEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BomWS
     */
    @WebEndpoint(name = "BomEndpointPort")
    public BomWS getBomEndpointPort() {
        return super.getPort(new QName("http://www.sportmaster.ru/plmbom", "BomEndpointPort"), BomWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BomWS
     */
    @WebEndpoint(name = "BomEndpointPort")
    public BomWS getBomEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.sportmaster.ru/plmbom", "BomEndpointPort"), BomWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOMENDPOINTSERVICE_EXCEPTION!= null) {
            throw BOMENDPOINTSERVICE_EXCEPTION;
        }
        return BOMENDPOINTSERVICE_WSDL_LOCATION;
    }

}
