//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.29 at 03:26:47 PM IST 
//


package com.burberry.wc.integration.productapi.bean;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

 	
    /**
     * Create an instance of {@link ProductAPI }
     * 
     */
    public static ProductAPI createProductAPI() {
        return new ProductAPI();
    }

	public static Source createProductAPIStyleSource() {
		return new Source();
	}

	public static CommodityCode createProductAPIStyleCommoditCode() {
		return new CommodityCode();
	}

	public static ProdPlaceholder createProductAPIStylePlaceholder() {
		return new ProdPlaceholder();
	}

	public static Season createProductAPIStyleProductSeasonSeason() {
		return new Season();
	}

	public static Colourway createProductAPIStyleColourway() {
		return new Colourway();
	}

	public static ProductSeason createProductAPIStyleProductSeason() {
		return new ProductSeason();
	}

	public static Material createProductAPIStyleMaterial() {
		return new Material();
	}

	public static Style createProductAPIStyle() {
		return new Style();
	}

	public static RiskManagement createProductAPIStyleRiskManagement() {
		return new RiskManagement();
	}

	public static ColourwaySeason createProductAPIStyleColourwayColourwaySeason() {
		return new ColourwaySeason();
	}

}
