
package com.sportmaster.wc.interfaces.webservices.carelabelbean;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.lcs.wc.util.LCSProperties;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CareLabelEndpointService", targetNamespace = "http://www.sportmaster.ru/plmcarelabel", wsdlLocation = "file:/D:/SM_WSDL/Care_Label_WSDL/PlmCareLabel.wsdl")
public class CareLabelEndpointService
    extends Service
{

    private final static URL CARELABELENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CARELABELENDPOINTSERVICE_EXCEPTION;
    private final static QName CARELABELENDPOINTSERVICE_QNAME = new QName("http://www.sportmaster.ru/plmcarelabel", "CareLabelEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
           // url = new URL("file:/D:/SM_WSDL/Care_Label_WSDL/PlmCareLabel.wsdl");
		    url = new URL(LCSProperties.get("com.sportmaster.wc.interfaces.webservices.outbound.carelabel.integration.wsdlLocation"));
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARELABELENDPOINTSERVICE_WSDL_LOCATION = url;
        CARELABELENDPOINTSERVICE_EXCEPTION = e;
    }

    public CareLabelEndpointService() {
        super(__getWsdlLocation(), CARELABELENDPOINTSERVICE_QNAME);
    }

    public CareLabelEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARELABELENDPOINTSERVICE_QNAME, features);
    }

    public CareLabelEndpointService(URL wsdlLocation) {
        super(wsdlLocation, CARELABELENDPOINTSERVICE_QNAME);
    }

    public CareLabelEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARELABELENDPOINTSERVICE_QNAME, features);
    }

    public CareLabelEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CareLabelEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CareLabelWS
     */
    @WebEndpoint(name = "CareLabelEndpointPort")
    public CareLabelWS getCareLabelEndpointPort() {
        return super.getPort(new QName("http://www.sportmaster.ru/plmcarelabel", "CareLabelEndpointPort"), CareLabelWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CareLabelWS
     */
    @WebEndpoint(name = "CareLabelEndpointPort")
    public CareLabelWS getCareLabelEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.sportmaster.ru/plmcarelabel", "CareLabelEndpointPort"), CareLabelWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARELABELENDPOINTSERVICE_EXCEPTION!= null) {
            throw CARELABELENDPOINTSERVICE_EXCEPTION;
        }
        return CARELABELENDPOINTSERVICE_WSDL_LOCATION;
    }

}
