
package com.sportmaster.wc.interfaces.webservices.carelabelbean;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CareLabelWS", targetNamespace = "http://www.sportmaster.ru/plmcarelabel")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CareLabelWS {


    /**
     * 
     * @param careLabelReportRequest
     * @return
     *     returns com.sportmaster.wc.interfaces.webservices.carelabelbean.CareLabelReportRequestResponse
     */
    @WebMethod
    @WebResult(name = "careLabelReportRequestResponse", targetNamespace = "http://www.sportmaster.ru/plmcarelabel", partName = "careLabelReportRequestResponse")
    public CareLabelReportRequestResponse careLabelReportRequest(
        @WebParam(name = "careLabelReportRequest", targetNamespace = "http://www.sportmaster.ru/plmcarelabel", partName = "careLabelReportRequest")
        CareLabelReportRequest careLabelReportRequest);

}
