package com.hbi.etl.dao;
// Generated Jan 12, 2015 4:54:46 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * HbiEtlTracker generated by hbm2java
 */
public class HbiEtlTracker  implements java.io.Serializable {


     private BigDecimal primarykey;
     private String runmode;
     private String status;
     private String apsexport;
     private String lawsonexport;
     private String ptc_str_1;
     private String ptc_str_2;
     private String ptc_str_3;
     private Date apsexporttime;
     private Date lawsonexporttime;
     private Date ptc_tms_1;
     private Date ptc_tms_2;
     private Date ptc_tms_3;
     private BigDecimal ptc_dbl_1;
     private BigDecimal ptc_dbl_2;
     private BigDecimal ptc_dbl_3;
     private Date loadercreatetime;
     private Date loaderupdatetime;
     private String datasourcesystem;
     private String vrdexport;
     private Date vrdexporttime;

    public HbiEtlTracker() {
    }

	
    public HbiEtlTracker(BigDecimal primarykey) {
        this.primarykey = primarykey;
    }
    public HbiEtlTracker(BigDecimal primarykey, String runmode, String status, String apsexport, String lawsonexport, String ptc_str_1, String ptc_str_2, String ptc_str_3, Date apsexporttime, Date lawsonexporttime, Date ptc_tms_1, Date ptc_tms_2, Date ptc_tms_3, BigDecimal ptc_dbl_1, BigDecimal ptc_dbl_2, BigDecimal ptc_dbl_3, Date loadercreatetime, Date loaderupdatetime, String datasourcesystem, String vrdexport, Date vrdexporttime) {
       this.primarykey = primarykey;
       this.runmode = runmode;
       this.status = status;
       this.apsexport = apsexport;
       this.lawsonexport = lawsonexport;
       this.ptc_str_1 = ptc_str_1;
       this.ptc_str_2 = ptc_str_2;
       this.ptc_str_3 = ptc_str_3;
       this.apsexporttime = apsexporttime;
       this.lawsonexporttime = lawsonexporttime;
       this.ptc_tms_1 = ptc_tms_1;
       this.ptc_tms_2 = ptc_tms_2;
       this.ptc_tms_3 = ptc_tms_3;
       this.ptc_dbl_1 = ptc_dbl_1;
       this.ptc_dbl_2 = ptc_dbl_2;
       this.ptc_dbl_3 = ptc_dbl_3;
       this.loadercreatetime = loadercreatetime;
       this.loaderupdatetime = loaderupdatetime;
       this.datasourcesystem = datasourcesystem;
       this.vrdexport = vrdexport;
       this.vrdexporttime = vrdexporttime;
    }


	public BigDecimal getPrimarykey() {
		return primarykey;
	}


	public void setPrimarykey(BigDecimal primarykey) {
		this.primarykey = primarykey;
	}


	public String getRunmode() {
		return runmode;
	}


	public void setRunmode(String runmode) {
		this.runmode = runmode;
	}


	public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}


	public String getApsexport() {
		return apsexport;
	}


	public void setApsexport(String apsexport) {
		this.apsexport = apsexport;
	}


	public String getLawsonexport() {
		return lawsonexport;
	}


	public void setLawsonexport(String lawsonexport) {
		this.lawsonexport = lawsonexport;
	}


	public String getPtc_str_1() {
		return ptc_str_1;
	}


	public void setPtc_str_1(String ptc_str_1) {
		this.ptc_str_1 = ptc_str_1;
	}


	public String getPtc_str_2() {
		return ptc_str_2;
	}


	public void setPtc_str_2(String ptc_str_2) {
		this.ptc_str_2 = ptc_str_2;
	}


	public String getPtc_str_3() {
		return ptc_str_3;
	}


	public void setPtc_str_3(String ptc_str_3) {
		this.ptc_str_3 = ptc_str_3;
	}


	public Date getApsexporttime() {
		return apsexporttime;
	}


	public void setApsexporttime(Date apsexporttime) {
		this.apsexporttime = apsexporttime;
	}


	public Date getLawsonexporttime() {
		return lawsonexporttime;
	}


	public void setLawsonexporttime(Date lawsonexporttime) {
		this.lawsonexporttime = lawsonexporttime;
	}


	public Date getPtc_tms_1() {
		return ptc_tms_1;
	}


	public void setPtc_tms_1(Date ptc_tms_1) {
		this.ptc_tms_1 = ptc_tms_1;
	}


	public Date getPtc_tms_2() {
		return ptc_tms_2;
	}


	public void setPtc_tms_2(Date ptc_tms_2) {
		this.ptc_tms_2 = ptc_tms_2;
	}


	public Date getPtc_tms_3() {
		return ptc_tms_3;
	}


	public void setPtc_tms_3(Date ptc_tms_3) {
		this.ptc_tms_3 = ptc_tms_3;
	}


	public BigDecimal getPtc_dbl_1() {
		return ptc_dbl_1;
	}


	public void setPtc_dbl_1(BigDecimal ptc_dbl_1) {
		this.ptc_dbl_1 = ptc_dbl_1;
	}


	public BigDecimal getPtc_dbl_2() {
		return ptc_dbl_2;
	}


	public void setPtc_dbl_2(BigDecimal ptc_dbl_2) {
		this.ptc_dbl_2 = ptc_dbl_2;
	}


	public BigDecimal getPtc_dbl_3() {
		return ptc_dbl_3;
	}


	public void setPtc_dbl_3(BigDecimal ptc_dbl_3) {
		this.ptc_dbl_3 = ptc_dbl_3;
	}


	public Date getLoadercreatetime() {
		return loadercreatetime;
	}


	public void setLoadercreatetime(Date loadercreatetime) {
		this.loadercreatetime = loadercreatetime;
	}


	


	public Date getLoaderupdatetime() {
		return loaderupdatetime;
	}


	public void setLoaderupdatetime(Date loaderupdatetime) {
		this.loaderupdatetime = loaderupdatetime;
	}


	public String getDatasourcesystem() {
		return datasourcesystem;
	}


	public void setDatasourcesystem(String datasourcesystem) {
		this.datasourcesystem = datasourcesystem;
	}


	public String getVrdexport() {
		return vrdexport;
	}


	public void setVrdexport(String vrdexport) {
		this.vrdexport = vrdexport;
	}


	public Date getVrdexporttime() {
		return vrdexporttime;
	}


	public void setVrdexporttime(Date vrdexporttime) {
		this.vrdexporttime = vrdexporttime;
	}
   
    


}


