//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.10-b140802.1033 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.28 at 01:32:45 PM IST 
//

package com.burberry.wc.integration.bean;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the generated package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 * 
 *
 * @version 'true' 1.0.1
 *
 * @author 'true' ITC INFOTECH
 *
 */
@XmlRegistry
public final class ObjectFactory {
	
	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: generated
	 * 
	 */
	private ObjectFactory() {
		
	}
	
	/**
	 * Create an instance of {@link Products }.
	 * 
	 */
	public static Products createProducts() {
		
		return new Products();
	}
	
	/**
	 * Create an instance of {@link Products.Style }.
	 * 
	 */
	public static Products.Style createProductsStyle() {
		
		return new Products.Style();
	}
	
	/**
	 * Create an instance of {@link Products.Style.Colourways }.
	 * 
	 */
	public static Products.Style.Colourways createProductColourways() {
		
		return new Products.Style.Colourways();
	}
	
	/**
	 * Create an instance of {@link Products.Style.Colourways.Colourway }.
	 * 
	 */
	public static Products.Style.Colourways.Colourway createProductColourway() {
		
		return new Products.Style.Colourways.Colourway();
	}
	
	/**
	 * Create an instance of {@link Products.Style.Colourways.Colourway.Seasons } .
	 * 
	 */
	public static Products.Style.Colourways.Colourway.Seasons createProductSeasons() {
		
		return new Products.Style.Colourways.Colourway.Seasons();
	}
	
	/**
	 * Create an instance of {@link Products.Style.Dimensions }.
	 * 
	 */
	public static Products.Style.Dimensions createProductsDimensions() {
		
		return new Products.Style.Dimensions();
	}
	
	/**
	 * Create an instance of {@link Products.Style.PlanningAttributes }.
	 * 
	 */
	public static Products.Style.PlanningAttributes createProductPlanningAttributes() {
		
		return new Products.Style.PlanningAttributes();
	}
	
	/**
	 * Create an instance of
	 * {@link Products.Style.Colourways.Colourway.Seasons.Season }.
	 * 
	 */
	public static Products.Style.Colourways.Colourway.Seasons.Season createProductSeason() {
		
		return new Products.Style.Colourways.Colourway.Seasons.Season();
	}
	
	/* Pricing specific bean method */
	
	/**
	 * Create an instance of {@link Pricing }.
	 * 
	 */
	public static Pricing createPricing() {
	
		return new Pricing();
	}
	
	/**
	 * Create an instance of {@link Pricing.PricingStyle }.
	 * 
	 */
	public static Pricing.PricingStyle createPricingStyle() {
	
		return new Pricing.PricingStyle();
	}
	
	/**
	 * Create an instance of {@link Pricing.PricingStyle.PricingColourways }.
	 * 
	 */
	public static Pricing.PricingStyle.PricingColourways createPricingColourways() {
	
		return new Pricing.PricingStyle.PricingColourways();
	}
	
	/**
	 * Create an instance of
	 * {@link Pricing.PricingStyle.PricingColourways.PricingColourway }.
	 * 
	 */
	public static Pricing.PricingStyle.PricingColourways.PricingColourway createPricingColourway() {
	
		return new Pricing.PricingStyle.PricingColourways.PricingColourway();
	}
	
	/**
	 * Create an instance of
	 * {@link Pricing.PricingStyle.PricingColourways.PricingColourway.PricingSeasons }
	 * .
	 * 
	 */
	public static Pricing.PricingStyle.PricingColourways.PricingColourway.PricingSeasons createPricingSeasons() {
	
		return new Pricing.PricingStyle.PricingColourways.PricingColourway.PricingSeasons();
	}
	
	/**
	 * Create an instance of
	 * {@link Pricing.PricingStyle.PricingColourways.PricingColourway.PricingSeasons.PricingSeason }
	 * .
	 * 
	 */
	public static Pricing.PricingStyle.PricingColourways.PricingColourway.PricingSeasons.PricingSeason createPricingSeason() {
	
		return new Pricing.PricingStyle.PricingColourways.PricingColourway.PricingSeasons.PricingSeason();
	}
	
}
