//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.21 at 04:07:27 PM IST 
//

package com.burberry.wc.integration.bean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "style" })
@XmlRootElement(name = "products")
public class Pricing implements Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private List<Pricing.PricingStyle> style;
	
	/**
	 * Gets the value of the style property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB String. This is why there is not a <CODE>set</CODE> method
	 * for the style property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getStyle().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Strings of the following type(s) are allowed in the list
	 * {@link Pricing.PricingStyle }
	 * 
	 * 
	 */
	public List<Pricing.PricingStyle> getStyle() {
	
		if (style == null) {
			style = new ArrayList<Pricing.PricingStyle>();
		}
		return this.style;
	}
	
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "style", propOrder = { "lastModifiedTimestamp", "colourways",
			"division", "brand", "operationalCategory", "type", "department",
			"subGroup", "ageGroup", "name", "mainRMId", "accessoryGroup" })
	public static class PricingStyle implements Serializable {
		
		private static final String ANY_SIMPLE_TYPE = "anySimpleType";
		
		private static final long serialVersionUID = 1L;
		
		@XmlElement(required = true)
		private String lastModifiedTimestamp;
		@XmlElement(required = true)
		private Pricing.PricingStyle.PricingColourways colourways;
		@XmlElement(required = true)
		private String division;
		@XmlElement(required = true)
		private String brand;
		@XmlElement(required = true)
		private String operationalCategory;
		@XmlElement(required = true)
		private String type;
		@XmlElement(required = true)
		private String department;
		@XmlElement(required = true)
		private String subGroup;
		private String ageGroup;
		@XmlElement(required = true)
		private String name;
		@XmlElement(required = true)
		private String mainRMId;
		private String accessoryGroup;
		@XmlAttribute(name = "id", required = true)
		@XmlSchemaType(name = ANY_SIMPLE_TYPE)
		private String id;
		@XmlAttribute(name = "legacyId")
		@XmlSchemaType(name = ANY_SIMPLE_TYPE)
		private String legacyId;
		
		/**
		 * Gets the value of the lastModifiedTimestamp property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getLastModifiedTimestamp() {
		
			return lastModifiedTimestamp;
		}
		
		/**
		 * Sets the value of the lastModifiedTimestamp property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setLastModifiedTimestamp(final String value) {
		
			this.lastModifiedTimestamp = value;
		}
		
		/**
		 * Gets the value of the colourways property.
		 * 
		 * @return possible String is {@link Pricing.PricingStyle.PricingColourways }
		 * 
		 */
		public Pricing.PricingStyle.PricingColourways getColourways() {
		
			return colourways;
		}
		
		/**
		 * Sets the value of the colourways property.
		 * 
		 * @param value
		 *          allowed String is {@link Pricing.PricingStyle.PricingColourways }
		 * 
		 */
		public void setColourways(final Pricing.PricingStyle.PricingColourways value) {
		
			this.colourways = value;
		}
		
		/**
		 * Gets the value of the division property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getDivision() {
		
			return division;
		}
		
		/**
		 * Sets the value of the division property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setDivision(final String value) {
		
			this.division = value;
		}
		
		/**
		 * Gets the value of the brand property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getBrand() {
		
			return brand;
		}
		
		/**
		 * Sets the value of the brand property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setBrand(final String value) {
		
			this.brand = value;
		}
		
		/**
		 * Gets the value of the operationalCategory property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getOperationalCategory() {
		
			return operationalCategory;
		}
		
		/**
		 * Sets the value of the operationalCategory property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setOperationalCategory(final String value) {
		
			this.operationalCategory = value;
		}
		
		/**
		 * Gets the value of the type property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getType() {
		
			return type;
		}
		
		/**
		 * Sets the value of the type property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setType(final String value) {
		
			this.type = value;
		}
		
		/**
		 * Gets the value of the department property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getDepartment() {
		
			return department;
		}
		
		/**
		 * Sets the value of the department property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setDepartment(final String value) {
		
			this.department = value;
		}
		
		/**
		 * Gets the value of the subGroup property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getSubGroup() {
		
			return subGroup;
		}
		
		/**
		 * Sets the value of the subGroup property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setSubGroup(final String value) {
		
			this.subGroup = value;
		}
		
		/**
		 * Gets the value of the ageGroup property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getAgeGroup() {
		
			return ageGroup;
		}
		
		/**
		 * Sets the value of the ageGroup property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setAgeGroup(final String value) {
		
			this.ageGroup = value;
		}
		
		/**
		 * Gets the value of the name property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getName() {
		
			return name;
		}
		
		/**
		 * Sets the value of the name property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setName(final String value) {
		
			this.name = value;
		}
		
		/**
		 * Gets the value of the mainRMId property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getMainRMId() {
		
			return mainRMId;
		}
		
		/**
		 * Sets the value of the mainRMId property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setMainRMId(final String value) {
		
			this.mainRMId = value;
		}
		
		/**
		 * Gets the value of the accessoryGroup property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getAccessoryGroup() {
		
			return accessoryGroup;
		}
		
		/**
		 * Sets the value of the accessoryGroup property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setAccessoryGroup(final String value) {
		
			this.accessoryGroup = value;
		}
		
		/**
		 * Gets the value of the id property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getId() {
		
			return id;
		}
		
		/**
		 * Sets the value of the id property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setId(final String value) {
		
			this.id = value;
		}
		
		/**
		 * Gets the value of the legacyId property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getLegacyId() {
		
			return legacyId;
		}
		
		/**
		 * Sets the value of the legacyId property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setLegacyId(final String value) {
		
			this.legacyId = value;
		}
		
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "colourways", propOrder = { "colourway" })
		public static class PricingColourways implements Serializable {
			
			private static final long serialVersionUID = 1L;
			@XmlElement(required = true)
			private List<Pricing.PricingStyle.PricingColourways.PricingColourway> colourway;
			
			/**
			 * Gets the value of the colourway property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned list will
			 * be present inside the JAXB String. This is why there is not a
			 * <CODE>set</CODE> method for the colourway property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getColourway().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Strings of the following type(s) are allowed in the list
			 * {@link Pricing.PricingStyle.PricingColourways.PricingColourway }
			 * 
			 * 
			 */
			public List<Pricing.PricingStyle.PricingColourways.PricingColourway> getColourway() {
			
				if (colourway == null) {
					colourway = new ArrayList<Pricing.PricingStyle.PricingColourways.PricingColourway>();
				}
				return this.colourway;
			}
			
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "colourway", propOrder = { "lastModifiedTimestamp",
					"seasons" })
			public static class PricingColourway implements Serializable {
				
				private static final long serialVersionUID = 1L;
				
				@XmlElement(required = true)
				private String lastModifiedTimestamp;
				@XmlElement(required = true)
				private Pricing.PricingStyle.PricingColourways.PricingColourway.PricingSeasons seasons;
				@XmlAttribute(name = "id", required = true)
				@XmlSchemaType(name = ANY_SIMPLE_TYPE)
				private String id;
				@XmlAttribute(name = "legacyId")
				@XmlSchemaType(name = ANY_SIMPLE_TYPE)
				private String legacyId;
				
				/**
				 * Gets the value of the lastModifiedTimestamp property.
				 * 
				 * @return possible String is {@link String }
				 * 
				 */
				public String getLastModifiedTimestamp() {
				
					return lastModifiedTimestamp;
				}
				
				/**
				 * Sets the value of the lastModifiedTimestamp property.
				 * 
				 * @param value
				 *          allowed String is {@link String }
				 * 
				 */
				public void setLastModifiedTimestamp(final String value) {
				
					this.lastModifiedTimestamp = value;
				}
				
				/**
				 * Gets the value of the seasons property.
				 * 
				 * @return possible String is
				 *         {@link Pricing.PricingStyle.PricingColourways.PricingColourway.PricingSeasons }
				 * 
				 */
				public Pricing.PricingStyle.PricingColourways.PricingColourway.PricingSeasons getSeasons() {
				
					return seasons;
				}
				
				/**
				 * Sets the value of the seasons property.
				 * 
				 * @param value
				 *          allowed String is
				 *          {@link Pricing.PricingStyle.PricingColourways.PricingColourway.PricingSeasons }
				 * 
				 */
				public void setSeasons(
						final Pricing.PricingStyle.PricingColourways.PricingColourway.PricingSeasons value) {
				
					this.seasons = value;
				}
				
				/**
				 * Gets the value of the id property.
				 * 
				 * @return possible String is {@link String }
				 * 
				 */
				public String getId() {
				
					return id;
				}
				
				/**
				 * Sets the value of the id property.
				 * 
				 * @param value
				 *          allowed String is {@link String }
				 * 
				 */
				public void setId(final String value) {
				
					this.id = value;
				}
				
				/**
				 * Gets the value of the legacyId property.
				 * 
				 * @return possible String is {@link String }
				 * 
				 */
				public String getLegacyId() {
				
					return legacyId;
				}
				
				/**
				 * Sets the value of the legacyId property.
				 * 
				 * @param value
				 *          allowed String is {@link String }
				 * 
				 */
				public void setLegacyId(final String value) {
				
					this.legacyId = value;
				}
				
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "seasons", propOrder = { "season" })
				public static class PricingSeasons implements Serializable {
					
					private static final long serialVersionUID = 1L;
					
					@XmlElement(required = true)
					private List<Pricing.PricingStyle.PricingColourways.PricingColourway.PricingSeasons.PricingSeason> season;
					
					/**
					 * Gets the value of the season property.
					 * 
					 * <p>
					 * This accessor method returns a reference to the live list, not a
					 * snapshot. Therefore any modification you make to the returned list
					 * will be present inside the JAXB String. This is why there is not a
					 * <CODE>set</CODE> method for the season property.
					 * 
					 * <p>
					 * For example, to add a new item, do as follows:
					 * 
					 * <pre>
					 * getSeason().add(newItem);
					 * </pre>
					 * 
					 * 
					 * <p>
					 * Strings of the following type(s) are allowed in the list
					 * {@link Pricing.PricingStyle.PricingColourways.PricingColourway.PricingSeasons.PricingSeason }
					 * 
					 * 
					 */
					public List<Pricing.PricingStyle.PricingColourways.PricingColourway.PricingSeasons.PricingSeason> getSeason() {
					
						if (season == null) {
							season = new ArrayList<Pricing.PricingStyle.PricingColourways.PricingColourway.PricingSeasons.PricingSeason>();
						}
						return this.season;
					}
					
					/**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="lastModifiedTimestamp">
                     *           &lt;simpleType>
                     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
                     *               &lt;length value="19"/>
                     *             &lt;/restriction>
                     *           &lt;/simpleType>
                     *         &lt;/element>
                     *         &lt;element name="collection" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                     *         &lt;element name="theme" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                     *         &lt;element name="fsr" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                     *         &lt;element name="vendorId" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                     *         &lt;element name="vendorName" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                     *         &lt;element name="vendorCountry" minOccurs="0">
                     *           &lt;simpleType>
                     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
                     *               &lt;length value="2"/>
                     *             &lt;/restriction>
                     *           &lt;/simpleType>
                     *         &lt;/element>
                     *         &lt;element name="colourwayCost" maxOccurs="unbounded">
                     *           &lt;complexType>
                     *             &lt;complexContent>
                     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *                 &lt;sequence>
                     *                   &lt;element name="costSheetNo" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                     *                   &lt;element name="finishedGoodsCost" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                     *                   &lt;element name="finishedGoodsCostCurrency" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                     *                   &lt;element name="finishedGoodsCostGBP" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                     *                   &lt;element name="landedCostGBP" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                     *                   &lt;element name="actualRetailGBP" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                     *                   &lt;element name="adjustedRetailEUR" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                     *                   &lt;element name="adjustedRetailUSD" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                     *                   &lt;element name="adjustedRetailHKD" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                     *                   &lt;element name="freightPercentage" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                     *                   &lt;element name="dutyPercentage" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                     *                   &lt;element name="costScenarioCOO" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                     *                 &lt;/sequence>
                     *               &lt;/restriction>
                     *             &lt;/complexContent>
                     *           &lt;/complexType>
                     *         &lt;/element>
                     *         &lt;element name="carryForward" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                     *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
                     *       &lt;/sequence>
                     *       &lt;attribute name="seasonId" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "lastModifiedTimestamp",
                        "collection",
                        "theme",
                        "fsr",
                        "vendorId",
                        "vendorName",
                        "vendorCountry",
                        "colourwayCost",
                        "carryForward",
                        "status"
                    })
					public static class PricingSeason implements Serializable {
						
						private static final long serialVersionUID = 1L;
						
						@XmlElement(required = true)
						private String lastModifiedTimestamp;
						private String collection;
						private String theme;
						private String fsr;
						private String vendorCountry;
						private String vendorId;
						private String vendorName;
						@XmlElement(required = true)
                        private List<Pricing.PricingStyle.PricingColourways.PricingColourway.PricingSeasons.PricingSeason.ColourwayCost> colourwayCost;
						private String carryForward;
						private String status;
						@XmlAttribute(name = "seasonId", required = true)
						@XmlSchemaType(name = ANY_SIMPLE_TYPE)
						private String seasonId;
						
						/**
						 * Gets the value of the lastModifiedTimestamp property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getLastModifiedTimestamp() {
						
							return lastModifiedTimestamp;
						}
						
						/**
						 * Sets the value of the lastModifiedTimestamp property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setLastModifiedTimestamp(final String value) {
						
							this.lastModifiedTimestamp = value;
						}
						
						/**
						 * Gets the value of the collection property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getCollection() {
						
							return collection;
						}
						
						/**
						 * Sets the value of the collection property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setCollection(final String value) {
						
							this.collection = value;
						}
						
						/**
						 * Gets the value of the theme property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getTheme() {
						
							return theme;
						}
						
						/**
						 * Sets the value of the theme property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setTheme(final String value) {
						
							this.theme = value;
						}
						
						/**
						 * Gets the value of the fsr property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getFsr() {
						
							return fsr;
						}
						
						/**
						 * Sets the value of the fsr property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setFsr(final String value) {
						
							this.fsr = value;
						}

						/**
						 * Gets the value of the vendorCountry property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getVendorCountry() {
						
							return vendorCountry;
						}

						/**
						 * Sets the value of the vendorCountry property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setVendorCountry(final String value) {
						
							this.vendorCountry = value;
						}
						
						/**
						 * Gets the value of the vendorId property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getVendorId() {
						
							return vendorId;
						}
						
						/**
						 * Sets the value of the vendorId property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setVendorId(final String value) {
						
							this.vendorId = value;
						}
						
						/**
						 * Gets the value of the vendorName property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getVendorName() {
						
							return vendorName;
						}
						
						/**
						 * Sets the value of the vendorName property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setVendorName(final String value) {
						
							this.vendorName = value;
						}
						
						/**
                         * Gets the value of the colourwayCost property.
                         * 
                         * <p>
                         * This accessor method returns a reference to the live list,
                         * not a snapshot. Therefore any modification you make to the
                         * returned list will be present inside the JAXB object.
                         * This is why there is not a <CODE>set</CODE> method for the colourwayCost property.
                         * 
                         * <p>
                         * For example, to add a new item, do as follows:
                         * <pre>
                         *    getColourwayCost().add(newItem);
                         * </pre>
                         * 
                         * 
                         * <p>
                         * Objects of the following type(s) are allowed in the list
                         * {@link Products.Style.Colourways.Colourway.Seasons.Season.ColourwayCost }
                         * 
                         * 
                         */
                        public List<ColourwayCost> getColourwayCost() {
                            if (colourwayCost == null) {
                                colourwayCost = new ArrayList<ColourwayCost>();
                            }
                            return this.colourwayCost;
                        }

						/**
						 * Gets the value of the carryForward property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getCarryForward() {
						
							return carryForward;
						}
						
						/**
						 * Sets the value of the carryForward property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setCarryForward(final String value) {
						
							this.carryForward = value;
						}
						
						/**
						 * Gets the value of the status property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getStatus() {
							
							return status;
						}
						
						/**
						 * Sets the value of the status property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setStatus(final String value) {
							
							this.status = value;
						}						
						
						/**
						 * Gets the value of the seasonId property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getSeasonId() {
						
							return seasonId;
						}
						
						/**
						 * Sets the value of the seasonId property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setSeasonId(final String value) {
						
							this.seasonId = value;
						}
						
						 /**
                         * <p>Java class for anonymous complex type.
                         * 
                         * <p>The following schema fragment specifies the expected content contained within this class.
                         * 
                         * <pre>
                         * &lt;complexType>
                         *   &lt;complexContent>
                         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                         *       &lt;sequence>
                         *         &lt;element name="costSheetNo" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                         *         &lt;element name="finishedGoodsCost" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                         *         &lt;element name="finishedGoodsCostCurrency" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                         *         &lt;element name="finishedGoodsCostGBP" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                         *         &lt;element name="landedCostGBP" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                         *         &lt;element name="actualRetailGBP" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                         *         &lt;element name="adjustedRetailEUR" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                         *         &lt;element name="adjustedRetailUSD" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                         *         &lt;element name="adjustedRetailHKD" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                         *         &lt;element name="freightPercentage" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                         *         &lt;element name="dutyPercentage" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                         *         &lt;element name="costScenarioCOO" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
                         *       &lt;/sequence>
                         *     &lt;/restriction>
                         *   &lt;/complexContent>
                         * &lt;/complexType>
                         * </pre>
                         * 
                         * 
                         */
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "costSheetNo",
                            "finishedGoodsCost",
                            "finishedGoodsCostCurrency",
                            "finishedGoodsCostGBP",
                            "landedCostGBP",
                            "actualRetailGBP",
                            "adjustedRetailEUR",
                            "adjustedRetailUSD",
                            "adjustedRetailHKD",
                            "freightPercentage",
                            "dutyPercentage",
                            "costScenarioCOO"
                        })
                        public static class ColourwayCost implements Serializable{

                            /**
							 * 
							 */
							private static final long serialVersionUID = 1L;
							private String costSheetNo;
                            private String finishedGoodsCost;
                            private String finishedGoodsCostCurrency;
                            private String finishedGoodsCostGBP;
                            private String landedCostGBP;
                            private String actualRetailGBP;
                            private String adjustedRetailEUR;
                            private String adjustedRetailUSD;
                            private String adjustedRetailHKD;
                            private String freightPercentage;
                            private String dutyPercentage;
                            private String costScenarioCOO;

                            /**
                             * Gets the value of the costSheetNo property.
                             * 
                             * @return
                             *     possible String is
                             *     {@link String }
                             *     
                             */
                            public String getCostSheetNo() {
                                return costSheetNo;
                            }

                            /**
                             * Sets the value of the costSheetNo property.
                             * 
                             * @param value
                             *     allowed String is
                             *     {@link String }
                             *     
                             */
                            public void setCostSheetNo(String value) {
                                this.costSheetNo = value;
                            }

                            /**
                             * Gets the value of the finishedGoodsCost property.
                             * 
                             * @return
                             *     possible String is
                             *     {@link String }
                             *     
                             */
                            public String getFinishedGoodsCost() {
                                return finishedGoodsCost;
                            }

                            /**
                             * Sets the value of the finishedGoodsCost property.
                             * 
                             * @param value
                             *     allowed String is
                             *     {@link String }
                             *     
                             */
                            public void setFinishedGoodsCost(String value) {
                                this.finishedGoodsCost = value;
                            }

                            /**
                             * Gets the value of the finishedGoodsCostCurrency property.
                             * 
                             * @return
                             *     possible String is
                             *     {@link String }
                             *     
                             */
                            public String getFinishedGoodsCostCurrency() {
                                return finishedGoodsCostCurrency;
                            }

                            /**
                             * Sets the value of the finishedGoodsCostCurrency property.
                             * 
                             * @param value
                             *     allowed String is
                             *     {@link String }
                             *     
                             */
                            public void setFinishedGoodsCostCurrency(String value) {
                                this.finishedGoodsCostCurrency = value;
                            }

                            /**
                             * Gets the value of the finishedGoodsCostGBP property.
                             * 
                             * @return
                             *     possible String is
                             *     {@link String }
                             *     
                             */
                            public String getFinishedGoodsCostGBP() {
                                return finishedGoodsCostGBP;
                            }

                            /**
                             * Sets the value of the finishedGoodsCostGBP property.
                             * 
                             * @param value
                             *     allowed String is
                             *     {@link String }
                             *     
                             */
                            public void setFinishedGoodsCostGBP(String value) {
                                this.finishedGoodsCostGBP = value;
                            }

                            /**
                             * Gets the value of the landedCostGBP property.
                             * 
                             * @return
                             *     possible String is
                             *     {@link String }
                             *     
                             */
                            public String getLandedCostGBP() {
                                return landedCostGBP;
                            }

                            /**
                             * Sets the value of the landedCostGBP property.
                             * 
                             * @param value
                             *     allowed String is
                             *     {@link String }
                             *     
                             */
                            public void setLandedCostGBP(String value) {
                                this.landedCostGBP = value;
                            }

                            /**
                             * Gets the value of the actualRetailGBP property.
                             * 
                             * @return
                             *     possible String is
                             *     {@link String }
                             *     
                             */
                            public String getActualRetailGBP() {
                                return actualRetailGBP;
                            }

                            /**
                             * Sets the value of the actualRetailGBP property.
                             * 
                             * @param value
                             *     allowed String is
                             *     {@link String }
                             *     
                             */
                            public void setActualRetailGBP(String value) {
                                this.actualRetailGBP = value;
                            }

                            /**
                             * Gets the value of the adjustedRetailEUR property.
                             * 
                             * @return
                             *     possible String is
                             *     {@link String }
                             *     
                             */
                            public String getAdjustedRetailEUR() {
                                return adjustedRetailEUR;
                            }

                            /**
                             * Sets the value of the adjustedRetailEUR property.
                             * 
                             * @param value
                             *     allowed String is
                             *     {@link String }
                             *     
                             */
                            public void setAdjustedRetailEUR(String value) {
                                this.adjustedRetailEUR = value;
                            }

                            /**
                             * Gets the value of the adjustedRetailUSD property.
                             * 
                             * @return
                             *     possible String is
                             *     {@link String }
                             *     
                             */
                            public String getAdjustedRetailUSD() {
                                return adjustedRetailUSD;
                            }

                            /**
                             * Sets the value of the adjustedRetailUSD property.
                             * 
                             * @param value
                             *     allowed String is
                             *     {@link String }
                             *     
                             */
                            public void setAdjustedRetailUSD(String value) {
                                this.adjustedRetailUSD = value;
                            }

                            /**
                             * Gets the value of the adjustedRetailHKD property.
                             * 
                             * @return
                             *     possible String is
                             *     {@link String }
                             *     
                             */
                            public String getAdjustedRetailHKD() {
                                return adjustedRetailHKD;
                            }

                            /**
                             * Sets the value of the adjustedRetailHKD property.
                             * 
                             * @param value
                             *     allowed String is
                             *     {@link String }
                             *     
                             */
                            public void setAdjustedRetailHKD(String value) {
                                this.adjustedRetailHKD = value;
                            }

                            /**
                             * Gets the value of the freightPercentage property.
                             * 
                             * @return
                             *     possible String is
                             *     {@link String }
                             *     
                             */
                            public String getFreightPercentage() {
                                return freightPercentage;
                            }

                            /**
                             * Sets the value of the freightPercentage property.
                             * 
                             * @param value
                             *     allowed String is
                             *     {@link String }
                             *     
                             */
                            public void setFreightPercentage(String value) {
                                this.freightPercentage = value;
                            }

                            /**
                             * Gets the value of the dutyPercentage property.
                             * 
                             * @return
                             *     possible String is
                             *     {@link String }
                             *     
                             */
                            public String getDutyPercentage() {
                                return dutyPercentage;
                            }

                            /**
                             * Sets the value of the dutyPercentage property.
                             * 
                             * @param value
                             *     allowed String is
                             *     {@link String }
                             *     
                             */
                            public void setDutyPercentage(String value) {
                                this.dutyPercentage = value;
                            }

                            /**
                             * Gets the value of the costScenarioCOO property.
                             * 
                             * @return
                             *     possible String is
                             *     {@link String }
                             *     
                             */
                            public String getCostScenarioCOO() {
                                return costScenarioCOO;
                            }

                            /**
                             * Sets the value of the costScenarioCOO property.
                             * 
                             * @param value
                             *     allowed String is
                             *     {@link String }
                             *     
                             */
                            public void setCostScenarioCOO(String value) {
                                this.costScenarioCOO = value;
                            }

                        }
						
					}
					
				}
				
			}
			
		}
		
	}
	
}
