//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.10-b140802.1033 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.28 at 01:32:45 PM IST 
//

package com.burberry.wc.integration.bean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "style" })
@XmlRootElement(name = "products")
public class Products implements Serializable{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private List<Products.Style> style;
	
	/**
	 * Gets the value of the style property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB String. This is why there is not a <CODE>set</CODE> method
	 * for the style property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getStyle().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Strings of the following type(s) are allowed in the list
	 * {@link Products.Style }
	 * 
	 * 
	 */
	public List<Products.Style> getStyle() {
		
		if (style == null) {
			style = new ArrayList<Products.Style>();
		}
		return this.style;
	}
	
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "lastModifiedTimestamp", "colourways",
			"division", "brand", "operationalCategory", "type", "department",
			"subGroup", "ageGroup", "name", "description", "marketingDescription",
			"sellingSizeRange", "mainRMId", "mainRMComposition",
			"citesClassification", "commodityCode", "materialPackagingGroup",
			"swingTicketType", "fabricConsumption", "dimensions",
			"planningAttributes", "heelHeight", "sizeGrouping", "branding",
			"checkBranding", "downWeight", "exotic", "fabricType", "fit", "shape",
			"silhouette", "styleDetailing", "kaff", "production", "world",
			"subWorld", "trimMaterial", "washCare", "accessoryGroup", "weightGroup" })
	public static class Style implements Serializable{
		
		/**
		 * 
		 */
		private static final long serialVersionUID = 1L;

		private static final String ANY_SIMPLE_TYPE = "anySimpleType";
		
		@XmlElement(required = true)
		private String lastModifiedTimestamp;
		@XmlElement(required = true)
		private Products.Style.Colourways colourways;
		@XmlElement(required = true)
		private String division;
		@XmlElement(required = true)
		private String brand;
		@XmlElement(required = true)
		private String operationalCategory;
		@XmlElement(required = true)
		private String type;
		@XmlElement(required = true)
		private String department;
		@XmlElement(required = true)
		private String subGroup;
		private String ageGroup;
		@XmlElement(required = true)
		private String name;
		@XmlElement(required = true)
		private String description;
		private String marketingDescription;
		@XmlElement(required = true)
		private String sellingSizeRange;
		@XmlElement(required = true)
		private String mainRMId;
		@XmlElement(required = true)
		private String mainRMComposition;
		@XmlElement(required = true)
		private String citesClassification;
		@XmlElement(required = true)
		private String commodityCode;
		@XmlElement(required = true)
		private String materialPackagingGroup;
		@XmlElement(required = true)
		private String swingTicketType;
		private String fabricConsumption;
		private Products.Style.Dimensions dimensions;
		private Products.Style.PlanningAttributes planningAttributes;
		private String heelHeight;
		private String sizeGrouping;
		private String branding;
		private String checkBranding;
		private String downWeight;
		private String exotic;
		private String fabricType;
		private String fit;
		private String shape;
		private String silhouette;
		private String styleDetailing;
		private String kaff;
		private String production;
		private String world;
		private String subWorld;
		private String trimMaterial;
		private String washCare;
		private String accessoryGroup;
		private String weightGroup;
		@XmlAttribute(name = "id", required = true)
		@XmlSchemaType(name = ANY_SIMPLE_TYPE)
		private String id;
		@XmlAttribute(name = "legacyId")
		@XmlSchemaType(name = ANY_SIMPLE_TYPE)
		private String legacyId;
		
		/**
		 * Gets the value of the lastModifiedTimestamp property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getLastModifiedTimestamp() {
			
			return lastModifiedTimestamp;
		}
		
		/**
		 * Sets the value of the lastModifiedTimestamp property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setLastModifiedTimestamp(final String value) {
			
			this.lastModifiedTimestamp = value;
		}
		
		/**
		 * Gets the value of the colourways property.
		 * 
		 * @return possible String is {@link Products.Style.Colourways }
		 * 
		 */
		public Products.Style.Colourways getColourways() {
			
			return colourways;
		}
		
		/**
		 * Sets the value of the colourways property.
		 * 
		 * @param value
		 *          allowed String is {@link Products.Style.Colourways }
		 * 
		 */
		public void setColourways(final Products.Style.Colourways value) {
			
			this.colourways = value;
		}
		
		/**
		 * Gets the value of the division property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getDivision() {
			
			return division;
		}
		
		/**
		 * Sets the value of the division property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setDivision(final String value) {
			
			this.division = value;
		}
		
		/**
		 * Gets the value of the brand property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getBrand() {
			
			return brand;
		}
		
		/**
		 * Sets the value of the brand property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setBrand(final String value) {
			
			this.brand = value;
		}
		
		/**
		 * Gets the value of the operationalCategory property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getOperationalCategory() {
			
			return operationalCategory;
		}
		
		/**
		 * Sets the value of the operationalCategory property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setOperationalCategory(final String value) {
			
			this.operationalCategory = value;
		}
		
		/**
		 * Gets the value of the type property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getType() {
			
			return type;
		}
		
		/**
		 * Sets the value of the type property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setType(final String value) {
			
			this.type = value;
		}
		
		/**
		 * Gets the value of the department property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getDepartment() {
			
			return department;
		}
		
		/**
		 * Sets the value of the department property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setDepartment(final String value) {
			
			this.department = value;
		}
		
		/**
		 * Gets the value of the subGroup property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getSubGroup() {
			
			return subGroup;
		}
		
		/**
		 * Sets the value of the subGroup property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setSubGroup(final String value) {
			
			this.subGroup = value;
		}
		
		/**
		 * Gets the value of the ageGroup property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getAgeGroup() {
			
			return ageGroup;
		}
		
		/**
		 * Sets the value of the ageGroup property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setAgeGroup(final String value) {
			
			this.ageGroup = value;
		}
		
		/**
		 * Gets the value of the name property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getName() {
			
			return name;
		}
		
		/**
		 * Sets the value of the name property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setName(final String value) {
			
			this.name = value;
		}
		
		/**
		 * Gets the value of the description property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getDescription() {
			
			return description;
		}
		
		/**
		 * Sets the value of the description property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setDescription(final String value) {
			
			this.description = value;
		}
		
		/**
		 * Gets the value of the marketingDescription property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getMarketingDescription() {
			
			return marketingDescription;
		}
		
		/**
		 * Sets the value of the marketingDescription property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setMarketingDescription(final String value) {
			
			this.marketingDescription = value;
		}
		
		/**
		 * Gets the value of the sellingSizeRange property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getSellingSizeRange() {
			
			return sellingSizeRange;
		}
		
		/**
		 * Sets the value of the sellingSizeRange property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setSellingSizeRange(final String value) {
			
			this.sellingSizeRange = value;
		}
		
		/**
		 * Gets the value of the mainRMId property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getMainRMId() {
			
			return mainRMId;
		}
		
		/**
		 * Sets the value of the mainRMId property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setMainRMId(final String value) {
			
			this.mainRMId = value;
		}
		
		/**
		 * Gets the value of the mainRMComposition property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getMainRMComposition() {
			
			return mainRMComposition;
		}
		
		/**
		 * Sets the value of the mainRMComposition property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setMainRMComposition(final String value) {
			
			this.mainRMComposition = value;
		}
		
		/**
		 * Gets the value of the citesClassification property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getCitesClassification() {
			
			return citesClassification;
		}
		
		/**
		 * Sets the value of the citesClassification property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setCitesClassification(final String value) {
			
			this.citesClassification = value;
		}
		
		/**
		 * Gets the value of the commodityCode property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getCommodityCode() {
			
			return commodityCode;
		}
		
		/**
		 * Sets the value of the commodityCode property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setCommodityCode(final String value) {
			
			this.commodityCode = value;
		}
		
		/**
		 * Gets the value of the materialPackagingGroup property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getMaterialPackagingGroup() {
			
			return materialPackagingGroup;
		}
		
		/**
		 * Sets the value of the materialPackagingGroup property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setMaterialPackagingGroup(final String value) {
			
			this.materialPackagingGroup = value;
		}
		
		/**
		 * Gets the value of the swingTicketType property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getSwingTicketType() {
			
			return swingTicketType;
		}
		
		/**
		 * Sets the value of the swingTicketType property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setSwingTicketType(final String value) {
			
			this.swingTicketType = value;
		}
		
		/**
		 * Gets the value of the fabricConsumption property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getFabricConsumption() {
			
			return fabricConsumption;
		}
		
		/**
		 * Sets the value of the fabricConsumption property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setFabricConsumption(final String value) {
			
			this.fabricConsumption = value;
		}
		
		/**
		 * Gets the value of the dimensions property.
		 * 
		 * @return possible String is {@link Products.Style.Dimensions }
		 * 
		 */
		public Products.Style.Dimensions getDimensions() {
			
			return dimensions;
		}
		
		/**
		 * Sets the value of the dimensions property.
		 * 
		 * @param value
		 *          allowed String is {@link Products.Style.Dimensions }
		 * 
		 */
		public void setDimensions(final Products.Style.Dimensions value) {
			
			this.dimensions = value;
		}
		
		/**
		 * Gets the value of the planningAttributes property.
		 * 
		 * @return possible String is {@link Products.Style.PlanningAttributes }
		 * 
		 */
		public Products.Style.PlanningAttributes getPlanningAttributes() {
			
			return planningAttributes;
		}
		
		/**
		 * Sets the value of the planningAttributes property.
		 * 
		 * @param value
		 *          allowed String is {@link Products.Style.PlanningAttributes }
		 * 
		 */
		public void setPlanningAttributes(
				final Products.Style.PlanningAttributes value) {
			
			this.planningAttributes = value;
		}
		
		/**
		 * Gets the value of the heelHeight property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getHeelHeight() {
			
			return heelHeight;
		}
		
		/**
		 * Sets the value of the heelHeight property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setHeelHeight(final String value) {
			
			this.heelHeight = value;
		}
		
		/**
		 * Gets the value of the sizeGrouping property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getSizeGrouping() {
			
			return sizeGrouping;
		}
		
		/**
		 * Sets the value of the sizeGrouping property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setSizeGrouping(final String value) {
			
			this.sizeGrouping = value;
		}
		
		/**
		 * Gets the value of the branding property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getBranding() {
			
			return branding;
		}
		
		/**
		 * Sets the value of the branding property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setBranding(final String value) {
			
			this.branding = value;
		}
		
		/**
		 * Gets the value of the checkBranding property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getCheckBranding() {
			
			return checkBranding;
		}
		
		/**
		 * Sets the value of the checkBranding property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setCheckBranding(final String value) {
			
			this.checkBranding = value;
		}
		
		/**
		 * Gets the value of the downWeight property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getDownWeight() {
			
			return downWeight;
		}
		
		/**
		 * Sets the value of the downWeight property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setDownWeight(final String value) {
			
			this.downWeight = value;
		}
		
		/**
		 * Gets the value of the exotic property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getExotic() {
			
			return exotic;
		}
		
		/**
		 * Sets the value of the exotic property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setExotic(final String value) {
			
			this.exotic = value;
		}
		
		/**
		 * Gets the value of the fabricType property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getFabricType() {
			
			return fabricType;
		}
		
		/**
		 * Sets the value of the fabricType property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setFabricType(final String value) {
			
			this.fabricType = value;
		}
		
		/**
		 * Gets the value of the fit property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getFit() {
			
			return fit;
		}
		
		/**
		 * Sets the value of the fit property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setFit(final String value) {
			
			this.fit = value;
		}
		
		/**
		 * Gets the value of the shape property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getShape() {
			
			return shape;
		}
		
		/**
		 * Sets the value of the shape property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setShape(final String value) {
			
			this.shape = value;
		}
		
		/**
		 * Gets the value of the silhouette property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getSilhouette() {
			
			return silhouette;
		}
		
		/**
		 * Sets the value of the silhouette property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setSilhouette(final String value) {
			
			this.silhouette = value;
		}
		
		/**
		 * Gets the value of the styleDetailing property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getStyleDetailing() {
			
			return styleDetailing;
		}
		
		/**
		 * Sets the value of the styleDetailing property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setStyleDetailing(final String value) {
			
			this.styleDetailing = value;
		}
		
		/**
		 * Gets the value of the kaff property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getKaff() {
			
			return kaff;
		}
		
		/**
		 * Sets the value of the kaff property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setKaff(final String value) {
			
			this.kaff = value;
		}
		
		/**
		 * Gets the value of the production property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getProduction() {
			
			return production;
		}
		
		/**
		 * Sets the value of the production property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setProduction(final String value) {
			
			this.production = value;
		}
		
		/**
		 * Gets the value of the world property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getWorld() {
			
			return world;
		}
		
		/**
		 * Sets the value of the world property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setWorld(final String value) {
			
			this.world = value;
		}
		
		/**
		 * Gets the value of the subWorld property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getSubWorld() {
			
			return subWorld;
		}
		
		/**
		 * Sets the value of the subWorld property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setSubWorld(final String value) {
			
			this.subWorld = value;
		}
		
		/**
		 * Gets the value of the trimMaterial property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getTrimMaterial() {
			
			return trimMaterial;
		}
		
		/**
		 * Sets the value of the trimMaterial property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setTrimMaterial(final String value) {
			
			this.trimMaterial = value;
		}
		
		/**
		 * Gets the value of the washCare property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getWashCare() {
			
			return washCare;
		}
		
		/**
		 * Sets the value of the washCare property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setWashCare(final String value) {
			
			this.washCare = value;
		}
		
		/**
		 * Gets the value of the accessoryGroup property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getAccessoryGroup() {
			
			return accessoryGroup;
		}
		
		/**
		 * Sets the value of the accessoryGroup property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setAccessoryGroup(final String value) {
			
			this.accessoryGroup = value;
		}
		
		/**
		 * Gets the value of the weightGroup property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getWeightGroup() {
			
			return weightGroup;
		}
		
		/**
		 * Sets the value of the weightGroup property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setWeightGroup(final String value) {
			
			this.weightGroup = value;
		}
		
		/**
		 * Gets the value of the id property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getId() {
			
			return id;
		}
		
		/**
		 * Sets the value of the id property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setId(final String value) {
			
			this.id = value;
		}
		
		/**
		 * Gets the value of the legacyId property.
		 * 
		 * @return possible String is {@link String }
		 * 
		 */
		public String getLegacyId() {
			
			return legacyId;
		}
		
		/**
		 * Sets the value of the legacyId property.
		 * 
		 * @param value
		 *          allowed String is {@link String }
		 * 
		 */
		public void setLegacyId(final String value) {
			
			this.legacyId = value;
		}
		
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "colourway" })
		public static class Colourways implements Serializable{
			
			/**
			 * 
			 */
			private static final long serialVersionUID = 1L;
			@XmlElement(required = true)
			private List<Products.Style.Colourways.Colourway> colourway;
			
			/**
			 * Gets the value of the colourway property.
			 * 
			 * <p>
			 * This accessor method returns a reference to the live list, not a
			 * snapshot. Therefore any modification you make to the returned list will
			 * be present inside the JAXB String. This is why there is not a
			 * <CODE>set</CODE> method for the colourway property.
			 * 
			 * <p>
			 * For example, to add a new item, do as follows:
			 * 
			 * <pre>
			 * getColourway().add(newItem);
			 * </pre>
			 * 
			 * 
			 * <p>
			 * Strings of the following type(s) are allowed in the list
			 * {@link Products.Style.Colourways.Colourway }
			 * 
			 * 
			 */
			public List<Products.Style.Colourways.Colourway> getColourway() {
				
				if (colourway == null) {
					colourway = new ArrayList<Products.Style.Colourways.Colourway>();
				}
				return this.colourway;
			}
			
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "lastModifiedTimestamp", "seasons",
					"colourGroup", "marketingColour", "colourCode", "colourType", "legacyColourCode",
					"gender", "checkDescription", "intent", "ip", "exitStrategy",
					"heritage", "iconic", "personalisable", "printPattern",
					"retailStartDate", "retailEndDate", "treatment" })
			public static class Colourway implements Serializable{
				
				/**
				 * 
				 */
				private static final long serialVersionUID = 1L;
				@XmlElement(required = true)
				private String lastModifiedTimestamp;
				@XmlElement(required = true)
				private Products.Style.Colourways.Colourway.Seasons seasons;
				@XmlElement(required = true)
				private String colourGroup;
				@XmlElement(required = true)
				private String marketingColour;
				@XmlElement(required = true)
				private String colourCode;
				private String colourType;
				private String legacyColourCode;
				@XmlElement(required = true)
				private String gender;
				private String checkDescription;
				private String intent;
				@XmlElement(name = "IP")
				private String ip;
				private String exitStrategy;
				private String heritage;
				private String iconic;
				private String personalisable;
				private String printPattern;
				private String retailStartDate;
				private String retailEndDate;
				private String treatment;
				@XmlAttribute(name = "id", required = true)
				@XmlSchemaType(name = ANY_SIMPLE_TYPE)
				private String id;
				@XmlAttribute(name = "legacyId")
				@XmlSchemaType(name = ANY_SIMPLE_TYPE)
				private String legacyId;
				
				/**
				 * Gets the value of the lastModifiedTimestamp property.
				 * 
				 * @return possible String is {@link String }
				 * 
				 */
				public String getLastModifiedTimestamp() {
					
					return lastModifiedTimestamp;
				}
				
				/**
				 * Sets the value of the lastModifiedTimestamp property.
				 * 
				 * @param value
				 *          allowed String is {@link String }
				 * 
				 */
				public void setLastModifiedTimestamp(final String value) {
					
					this.lastModifiedTimestamp = value;
				}
				
				/**
				 * Gets the value of the seasons property.
				 * 
				 * @return possible String is
				 *         {@link Products.Style.Colourways.Colourway.Seasons }
				 * 
				 */
				public Products.Style.Colourways.Colourway.Seasons getSeasons() {
					
					return seasons;
				}
				
				/**
				 * Sets the value of the seasons property.
				 * 
				 * @param value
				 *          allowed String is
				 *          {@link Products.Style.Colourways.Colourway.Seasons }
				 * 
				 */
				public void setSeasons(
						final Products.Style.Colourways.Colourway.Seasons value) {
					
					this.seasons = value;
				}
				
				/**
				 * Gets the value of the colourGroup property.
				 * 
				 * @return possible String is {@link String }
				 * 
				 */
				public String getColourGroup() {
					
					return colourGroup;
				}
				
				/**
				 * Sets the value of the colourGroup property.
				 * 
				 * @param value
				 *          allowed String is {@link String }
				 * 
				 */
				public void setColourGroup(final String value) {
					
					this.colourGroup = value;
				}
				
				/**
				 * Gets the value of the marketingColour property.
				 * 
				 * @return possible String is {@link String }
				 * 
				 */
				public String getMarketingColour() {
					
					return marketingColour;
				}
				
				/**
				 * Sets the value of the marketingColour property.
				 * 
				 * @param value
				 *          allowed String is {@link String }
				 * 
				 */
				public void setMarketingColour(final String value) {
					
					this.marketingColour = value;
				}
				
				/**
				 * Gets the value of the colourCode property.
				 * 
				 * @return possible String is {@link String }
				 * 
				 */
				public String getColourCode() {
					
					return colourCode;
				}
				
				/**
				 * Sets the value of the colourCode property.
				 * 
				 * @param value
				 *          allowed String is {@link String }
				 * 
				 */
				public void setColourCode(final String value) {
					
					this.colourCode = value;
				}

				/**
				 * Gets the value of the colourType property.
				 * 
				 * @return possible String is {@link String }
				 * 
				 */
				public String getColourType() {
					
					return colourType;
				}
				
				/**
				 * Sets the value of the colourType property.
				 * 
				 * @param value
				 *          allowed String is {@link String }
				 * 
				 */
				public void setColourType(final String value) {
					
					this.colourType = value;
				}
				
				/**
				 * Gets the value of the legacyColourCode property.
				 * 
				 * @return possible String is {@link String }
				 * 
				 */
				public String getLegacyColourCode() {
					
					return legacyColourCode;
				}
				
				/**
				 * Sets the value of the legacyColourCode property.
				 * 
				 * @param value
				 *          allowed String is {@link String }
				 * 
				 */
				public void setLegacyColourCode(final String value) {
					
					this.legacyColourCode = value;
				}
				
				/**
				 * Gets the value of the gender property.
				 * 
				 * @return possible String is {@link String }
				 * 
				 */
				public String getGender() {
					
					return gender;
				}
				
				/**
				 * Sets the value of the gender property.
				 * 
				 * @param value
				 *          allowed String is {@link String }
				 * 
				 */
				public void setGender(final String value) {
					
					this.gender = value;
				}
				
				/**
				 * Gets the value of the checkDescription property.
				 * 
				 * @return possible String is {@link String }
				 * 
				 */
				public String getCheckDescription() {
					
					return checkDescription;
				}
				
				/**
				 * Sets the value of the checkDescription property.
				 * 
				 * @param value
				 *          allowed String is {@link String }
				 * 
				 */
				public void setCheckDescription(final String value) {
					
					this.checkDescription = value;
				}
				
				/**
				 * Gets the value of the intent property.
				 * 
				 * @return possible String is {@link String }
				 * 
				 */
				public String getIntent() {
					
					return intent;
				}
				
				/**
				 * Sets the value of the intent property.
				 * 
				 * @param value
				 *          allowed String is {@link String }
				 * 
				 */
				public void setIntent(final String value) {
					
					this.intent = value;
				}
				
				/**
				 * Gets the value of the ip property.
				 * 
				 * @return possible String is {@link String }
				 * 
				 */
				public String getIP() {
					
					return ip;
				}
				
				/**
				 * Sets the value of the ip property.
				 * 
				 * @param value
				 *          allowed String is {@link String }
				 * 
				 */
				public void setIP(final String value) {
					
					this.ip = value;
				}
				
				/**
				 * Gets the value of the exitStrategy property.
				 * 
				 * @return possible String is {@link String }
				 * 
				 */
				public String getExitStrategy() {
					
					return exitStrategy;
				}
				
				/**
				 * Sets the value of the exitStrategy property.
				 * 
				 * @param value
				 *          allowed String is {@link String }
				 * 
				 */
				public void setExitStrategy(final String value) {
					
					this.exitStrategy = value;
				}
				
				/**
				 * Gets the value of the heritage property.
				 * 
				 * @return possible String is {@link String }
				 * 
				 */
				public String getHeritage() {
					
					return heritage;
				}
				
				/**
				 * Sets the value of the heritage property.
				 * 
				 * @param value
				 *          allowed String is {@link String }
				 * 
				 */
				public void setHeritage(final String value) {
					
					this.heritage = value;
				}
				
				/**
				 * Gets the value of the iconic property.
				 * 
				 * @return possible String is {@link String }
				 * 
				 */
				public String getIconic() {
					
					return iconic;
				}
				
				/**
				 * Sets the value of the iconic property.
				 * 
				 * @param value
				 *          allowed String is {@link String }
				 * 
				 */
				public void setIconic(final String value) {
					
					this.iconic = value;
				}
				
				/**
				 * Gets the value of the personalisable property.
				 * 
				 * @return possible String is {@link String }
				 * 
				 */
				public String getPersonalisable() {
					
					return personalisable;
				}
				
				/**
				 * Sets the value of the personalisable property.
				 * 
				 * @param value
				 *          allowed String is {@link String }
				 * 
				 */
				public void setPersonalisable(final String value) {
					
					this.personalisable = value;
				}
				
				/**
				 * Gets the value of the printPattern property.
				 * 
				 * @return possible String is {@link String }
				 * 
				 */
				public String getPrintPattern() {
					
					return printPattern;
				}
				
				/**
				 * Sets the value of the printPattern property.
				 * 
				 * @param value
				 *          allowed String is {@link String }
				 * 
				 */
				public void setPrintPattern(final String value) {
					
					this.printPattern = value;
				}
				
				/**
				 * Gets the value of the retailStartDate property.
				 * 
				 * @return possible String is {@link String }
				 * 
				 */
				public String getRetailStartDate() {
					
					return retailStartDate;
				}
				
				/**
				 * Sets the value of the retailStartDate property.
				 * 
				 * @param value
				 *          allowed String is {@link String }
				 * 
				 */
				public void setRetailStartDate(final String value) {
					
					this.retailStartDate = value;
				}
				
				/**
				 * Gets the value of the retailEndDate property.
				 * 
				 * @return possible String is {@link String }
				 * 
				 */
				public String getRetailEndDate() {
					
					return retailEndDate;
				}
				
				/**
				 * Sets the value of the retailEndDate property.
				 * 
				 * @param value
				 *          allowed String is {@link String }
				 * 
				 */
				public void setRetailEndDate(final String value) {
					
					this.retailEndDate = value;
				}
				
				/**
				 * Gets the value of the treatment property.
				 * 
				 * @return possible String is {@link String }
				 * 
				 */
				public String getTreatment() {
					
					return treatment;
				}
				
				/**
				 * Sets the value of the treatment property.
				 * 
				 * @param value
				 *          allowed String is {@link String }
				 * 
				 */
				public void setTreatment(final String value) {
					
					this.treatment = value;
				}
				
				/**
				 * Gets the value of the id property.
				 * 
				 * @return possible String is {@link String }
				 * 
				 */
				public String getId() {
					
					return id;
				}
				
				/**
				 * Sets the value of the id property.
				 * 
				 * @param value
				 *          allowed String is {@link String }
				 * 
				 */
				public void setId(final String value) {
					
					this.id = value;
				}
				
				/**
				 * Gets the value of the legacyId property.
				 * 
				 * @return possible String is {@link String }
				 * 
				 */
				public String getLegacyId() {
					
					return legacyId;
				}
				
				/**
				 * Sets the value of the legacyId property.
				 * 
				 * @param value
				 *          allowed String is {@link String }
				 * 
				 */
				public void setLegacyId(final String value) {
					
					this.legacyId = value;
				}
				
				@XmlAccessorType(XmlAccessType.FIELD)
				@XmlType(name = "", propOrder = { "season" })
				public static class Seasons implements Serializable{
					
					/**
					 * 
					 */
					private static final long serialVersionUID = 1L;
					@XmlElement(required = true)
					private List<Products.Style.Colourways.Colourway.Seasons.Season> season;
					
					/**
					 * Gets the value of the season property.
					 * 
					 * <p>
					 * This accessor method returns a reference to the live list, not a
					 * snapshot. Therefore any modification you make to the returned list
					 * will be present inside the JAXB String. This is why there is not a
					 * <CODE>set</CODE> method for the season property.
					 * 
					 * <p>
					 * For example, to add a new item, do as follows:
					 * 
					 * <pre>
					 * getSeason().add(newItem);
					 * </pre>
					 * 
					 * 
					 * <p>
					 * Strings of the following type(s) are allowed in the list
					 * {@link Products.Style.Colourways.Colourway.Seasons.Season }
					 * 
					 * 
					 */
					public List<Products.Style.Colourways.Colourway.Seasons.Season> getSeason() {
						
						if (season == null) {
							season = new ArrayList<Products.Style.Colourways.Colourway.Seasons.Season>();
						}
						return this.season;
					}
					
					@XmlAccessorType(XmlAccessType.FIELD)
					@XmlType(name = "", propOrder = { "lastModifiedTimestamp",
							"adCampaign", "brandBuy", "lookBook", "capsule", "carryForward",
							"carryOutCode", "stillValidReason", "climate", "collection",
							"theme", "status", "fixture", "fsr","core" ,"gsr", "keyDriver",
							"limitedAvailability", "runway", "overmakes", "startDate", "endDate",
							"coo", "vendorId", "vendorName" })
					public static class Season implements Serializable {
						
						/**
						 * 
						 */
						private static final long serialVersionUID = 1L;
						@XmlElement(required = true)
						private String lastModifiedTimestamp;
						private String adCampaign;
						private String brandBuy;
						private String lookBook;
						private String capsule;
						private String carryForward;
						private String carryOutCode;
						private String stillValidReason;
						private String climate;
						private String collection;
						private String theme;
						private String status;
						private String fixture;
						private String fsr;
						private String core;
						private String gsr;
						private String keyDriver;
						private String limitedAvailability;
						private String runway;
						private String overmakes;
						private String startDate;
						private String endDate;
						private String coo;
						private String vendorId;
						private String vendorName;
						@XmlAttribute(name = "id", required = true)
						@XmlSchemaType(name = ANY_SIMPLE_TYPE)
						private String id;
						
						/**
						 * Gets the value of the lastModifiedTimestamp property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getLastModifiedTimestamp() {
							
							return lastModifiedTimestamp;
						}
						
						/**
						 * Sets the value of the lastModifiedTimestamp property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setLastModifiedTimestamp(final String value) {
							
							this.lastModifiedTimestamp = value;
						}
						
						/**
						 * Gets the value of the adCampaign property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getAdCampaign() {
							
							return adCampaign;
						}
						
						/**
						 * Sets the value of the adCampaign property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setAdCampaign(final String value) {
							
							this.adCampaign = value;
						}
						
						/**
						 * Gets the value of the brandBuy property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getBrandBuy() {
							
							return brandBuy;
						}
						
						/**
						 * Sets the value of the brandBuy property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setBrandBuy(final String value) {
							
							this.brandBuy = value;
						}

						/**
						 * Gets the value of the lookBook property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getLookBook() {
							
							return lookBook;
						}
						
						/**
						 * Sets the value of the lookBook property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setLookBook(final String value) {
							
							this.lookBook = value;
						}
						
						/**
						 * Gets the value of the capsule property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getCapsule() {
							
							return capsule;
						}
						
						/**
						 * Sets the value of the capsule property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setCapsule(final String value) {
							
							this.capsule = value;
						}
						
						/**
						 * Gets the value of the carryForward property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getCarryForward() {
							
							return carryForward;
						}
						
						/**
						 * Sets the value of the carryForward property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setCarryForward(final String value) {
							
							this.carryForward = value;
						}
						
						/**
						 * Gets the value of the carryOutCode property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getCarryOutCode() {
							
							return carryOutCode;
						}
						
						/**
						 * Sets the value of the carryOutCode property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setCarryOutCode(final String value) {
							
							this.carryOutCode = value;
						}
						
						/**
						 * Gets the value of the stillValidReason property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getStillValidReason() {
							
							return stillValidReason;
						}
						
						/**
						 * Sets the value of the stillValidReason property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setStillValidReason(final String value) {
							
							this.stillValidReason = value;
						}
						
						/**
						 * Gets the value of the climate property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getClimate() {
							
							return climate;
						}
						
						/**
						 * Sets the value of the climate property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setClimate(final String value) {
							
							this.climate = value;
						}
						
						/**
						 * Gets the value of the collection property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getCollection() {
							
							return collection;
						}
						
						/**
						 * Sets the value of the collection property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setCollection(final String value) {
							
							this.collection = value;
						}
						
						/**
						 * Gets the value of the theme property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getTheme() {
							
							return theme;
						}
						
						/**
						 * Sets the value of the theme property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setTheme(final String value) {
							
							this.theme = value;
						}
						
						/**
						 * Gets the value of the status property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getStatus() {
							
							return status;
						}
						
						/**
						 * Sets the value of the status property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setStatus(final String value) {
							
							this.status = value;
						}
						
						/**
						 * Gets the value of the fixture property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getFixture() {
							
							return fixture;
						}
						
						/**
						 * Sets the value of the fixture property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setFixture(final String value) {
							
							this.fixture = value;
						}
						
						/**
						 * Gets the value of the fsr property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getFsr() {
							
							return fsr;
						}
						
						/**
						 * Sets the value of the fsr property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setFsr(final String value) {
							
							this.fsr = value;
						}
						
						/**
						 * Gets the value of the core property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getCore() {
							
							return core;
						}
						
						/**
						 * Sets the value of the cire property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setCore(final String value) {
							
							this.core = value;
						}
						/**
						 * Gets the value of the gsr property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getGsr() {
							
							return gsr;
						}
						
						/**
						 * Sets the value of the gsr property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setGsr(final String value) {
							
							this.gsr = value;
						}
						
						/**
						 * Gets the value of the keyDriver property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getKeyDriver() {
							
							return keyDriver;
						}
						
						/**
						 * Sets the value of the keyDriver property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setKeyDriver(final String value) {
							
							this.keyDriver = value;
						}
						
						/**
						 * Gets the value of the limitedAvailability property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getLimitedAvailability() {
							
							return limitedAvailability;
						}
						
						/**
						 * Sets the value of the limitedAvailability property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setLimitedAvailability(final String value) {
							
							this.limitedAvailability = value;
						}

                        /**
                         * Gets the value of the runway property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link Object }
                         *     
                         */
                        public Object getRunway() {
                            return runway;
                        }

                        /**
                         * Sets the value of the runway property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link Object }
                         *     
                         */
                        public void setRunway(final String value) {
                            this.runway = value;
                        }
						
						/**
						 * Gets the value of the overmakes property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getOvermakes() {
							
							return overmakes;
						}
						
						/**
						 * Sets the value of the overmakes property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setOvermakes(final String value) {
							
							this.overmakes = value;
						}
						
						/**
						 * Gets the value of the startDate property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getStartDate() {
							
							return startDate;
						}
						
						/**
						 * Sets the value of the startDate property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setStartDate(final String value) {
							
							this.startDate = value;
						}
						
						/**
						 * Gets the value of the endDate property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getEndDate() {
							
							return endDate;
						}
						
						/**
						 * Sets the value of the endDate property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setEndDate(final String value) {
							
							this.endDate = value;
						}
						
						/**
						 * Gets the value of the coo property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getCoo() {
							
							return coo;
						}
						
						/**
						 * Sets the value of the coo property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setCoo(final String value) {
							
							this.coo = value;
						}
						
						/**
						 * Gets the value of the vendorId property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getVendorId() {
							
							return vendorId;
						}
						
						/**
						 * Sets the value of the vendorId property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setVendorId(final String value) {
							
							this.vendorId = value;
						}
						
						/**
						 * Gets the value of the vendorName property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getVendorName() {
							
							return vendorName;
						}
						
						/**
						 * Sets the value of the vendorName property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setVendorName(final String value) {
							
							this.vendorName = value;
						}
						
						/**
						 * Gets the value of the id property.
						 * 
						 * @return possible String is {@link String }
						 * 
						 */
						public String getId() {
							
							return id;
						}
						
						/**
						 * Sets the value of the id property.
						 * 
						 * @param value
						 *          allowed String is {@link String }
						 * 
						 */
						public void setId(final String value) {
							
							this.id = value;
						}
						
					}
					
				}
				
			}
			
		}
		
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				
		})
		public static class Dimensions implements Serializable{
			
			/**
			 * 
			 */
			private static final long serialVersionUID = 1L;
			private String heightCM;
			private String widthCM;
			private String lengthCM;
			
			/**
			 * Gets the value of the heightCM property.
			 * 
			 * @return possible String is {@link String }
			 * 
			 */
			public String getHeightCM() {
				
				return heightCM;
			}
			
			/**
			 * Sets the value of the heightCM property.
			 * 
			 * @param value
			 *          allowed String is {@link String }
			 * 
			 */
			public void setHeightCM(final String value) {
				
				this.heightCM = value;
			}
			
			/**
			 * Gets the value of the widthCM property.
			 * 
			 * @return possible String is {@link String }
			 * 
			 */
			public String getWidthCM() {
				
				return widthCM;
			}
			
			/**
			 * Sets the value of the widthCM property.
			 * 
			 * @param value
			 *          allowed String is {@link String }
			 * 
			 */
			public void setWidthCM(final String value) {
				
				this.widthCM = value;
			}
			
			/**
			 * Gets the value of the lengthCM property.
			 * 
			 * @return possible String is {@link String }
			 * 
			 */
			public String getLengthCM() {
				
				return lengthCM;
			}
			
			/**
			 * Sets the value of the lengthCM property.
			 * 
			 * @param value
			 *          allowed String is {@link String }
			 * 
			 */
			public void setLengthCM(final String value) {
				
				this.lengthCM = value;
			}
			
		}
		
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = {
				
		})
		public static class PlanningAttributes implements Serializable{
			
			/**
			 * 
			 */
			private static final long serialVersionUID = 1L;
			private String length;
			private String sleeve;
			private String planGroup;
			
			/**
			 * Gets the value of the length property.
			 * 
			 * @return possible String is {@link String }
			 * 
			 */
			public String getLength() {
				
				return length;
			}
			
			/**
			 * Sets the value of the length property.
			 * 
			 * @param value
			 *          allowed String is {@link String }
			 * 
			 */
			public void setLength(final String value) {
				
				this.length = value;
			}
			
			/**
			 * Gets the value of the sleeve property.
			 * 
			 * @return possible String is {@link String }
			 * 
			 */
			public String getSleeve() {
				
				return sleeve;
			}
			
			/**
			 * Sets the value of the sleeve property.
			 * 
			 * @param value
			 *          allowed String is {@link String }
			 * 
			 */
			public void setSleeve(final String value) {
				
				this.sleeve = value;
			}
			
			/**
			 * Gets the value of the planGroup property.
			 * 
			 * @return possible String is {@link String }
			 * 
			 */
			public String getPlanGroup() {
				
				return planGroup;
			}
			
			/**
			 * Sets the value of the planGroup property.
			 * 
			 * @param value
			 *          allowed String is {@link String }
			 * 
			 */
			public void setPlanGroup(final String value) {
				
				this.planGroup = value;
			}
			
		}
		
	}
	
}
