package com.hbi.etl.dao;
// Generated Sep 11, 2014 2:03:38 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.Date;

/**
 * HbiMoaObject generated by hbm2java
 */
public class HbiMoaObject  implements java.io.Serializable {


     private BigDecimal primarykey;
     private String ptc_str_1;
     private String ptc_str_2;
     private String ptc_str_3;
     private String ptc_str_4;
     private String ptc_str_5;
     private String ptc_str_6;
     private String ptc_str_7;
     private String ptc_str_8;
     private String ptc_str_9;
     private String ptc_str_10;
     private String ptc_str_11;
     private String ptc_str_12;
     private String ptc_str_13;
     private String ptc_str_14;
     private String ptc_str_15;
     private String ptc_str_16;
     private String ptc_str_17;
     private String ptc_str_18;
     private String ptc_str_19;
     private String ptc_str_20;
     private String ptc_str_21;
     private String ptc_str_22;
     private String ptc_str_23;
     private String ptc_str_24;
     private String ptc_str_25;
     private String ptc_str_26;
     private String ptc_str_27;
     private String ptc_str_28;
     private String ptc_str_29;
     private String ptc_str_30;
     private Date ptc_tms_1;
     private Date ptc_tms_10;
     private Date ptc_tms_2;
     private Date ptc_tms_3;
     private Date ptc_tms_4;
     private Date ptc_tms_5;
     private Date ptc_tms_6;
     private Date ptc_tms_7;
     private Date ptc_tms_8;
     private Date ptc_tms_9;
     private BigDecimal ptc_dbl_1;
     private BigDecimal ptc_dbl_2;
     private BigDecimal ptc_dbl_3;
     private BigDecimal ptc_dbl_4;
     private BigDecimal ptc_dbl_5;
     private BigDecimal ptc_dbl_6;
     private BigDecimal ptc_dbl_7;
     private BigDecimal ptc_dbl_8;
     private BigDecimal ptc_dbl_9;
     private BigDecimal ptc_dbl_10;
     private BigDecimal ptc_dbl_11;
     private BigDecimal ptc_dbl_12;
     private BigDecimal ptc_dbl_13;
     private BigDecimal ptc_dbl_14;
     private BigDecimal ptc_dbl_15;
     private BigDecimal ptc_dbl_16;
     private BigDecimal ptc_dbl_17;
     private BigDecimal ptc_dbl_18;
     private BigDecimal ptc_dbl_19;
     private BigDecimal ptc_dbl_20;
     private BigDecimal ptc_dbl_21;
     private BigDecimal ptc_dbl_22;
     private BigDecimal ptc_dbl_23;
     private BigDecimal ptc_dbl_24;
     private BigDecimal ptc_dbl_25;
     private BigDecimal ptc_dbl_26;
     private BigDecimal ptc_dbl_27;
     private BigDecimal ptc_dbl_28;
     private BigDecimal ptc_dbl_29;
     private BigDecimal ptc_dbl_30;
     private Boolean dropped;
     private Date effectindate;
     private Boolean effectlatest;
     private Date effectoutdate;
     private BigDecimal effectsequence;
     private String flextypeidpath;
     private String classnamekeya4;
     private BigDecimal ida3a4;
     private String classnamekeyb5;
     private BigDecimal ida3b5;
     private String ownerversion;
     private BigDecimal sortingnumber;
     private Date createstampa2;
     private BigDecimal markfordeletea2;
     private Date updatestampa2;
     private BigDecimal branchid;
     private String ownerref;
     private BigDecimal ownerkey;
     private String attributekey;
     private String attributevalue;
     private Date loadercreatetime;
     private Date loaderupdatetime;
     private BigDecimal ida2a2;
     private String datasourcesystem;

    public HbiMoaObject() {
    }

	
    public HbiMoaObject(BigDecimal ida2a2) {
        this.ida2a2 = ida2a2;
    }
    public HbiMoaObject(String ptc_str_1, String ptc_str_2, String ptc_str_3, String ptc_str_4, String ptc_str_5, String ptc_str_6, String ptc_str_7, String ptc_str_8, String ptc_str_9, String ptc_str_10, String ptc_str_11, String ptc_str_12, String ptc_str_13, String ptc_str_14, String ptc_str_15, String ptc_str_16, String ptc_str_17, String ptc_str_18, String ptc_str_19, String ptc_str_20, String ptc_str_21, String ptc_str_22, String ptc_str_23, String ptc_str_24, String ptc_str_25, String ptc_str_26, String ptc_str_27, String ptc_str_28, String ptc_str_29, String ptc_str_30, Date ptc_tms_1, Date ptc_tms_10, Date ptc_tms_2, Date ptc_tms_3, Date ptc_tms_4, Date ptc_tms_5, Date ptc_tms_6, Date ptc_tms_7, Date ptc_tms_8, Date ptc_tms_9, BigDecimal ptc_dbl_1, BigDecimal ptc_dbl_2, BigDecimal ptc_dbl_3, BigDecimal ptc_dbl_4, BigDecimal ptc_dbl_5, BigDecimal ptc_dbl_6, BigDecimal ptc_dbl_7, BigDecimal ptc_dbl_8, BigDecimal ptc_dbl_9, BigDecimal ptc_dbl_10, BigDecimal ptc_dbl_11, BigDecimal ptc_dbl_12, BigDecimal ptc_dbl_13, BigDecimal ptc_dbl_14, BigDecimal ptc_dbl_15, BigDecimal ptc_dbl_16, BigDecimal ptc_dbl_17, BigDecimal ptc_dbl_18, BigDecimal ptc_dbl_19, BigDecimal ptc_dbl_20, BigDecimal ptc_dbl_21, BigDecimal ptc_dbl_22, BigDecimal ptc_dbl_23, BigDecimal ptc_dbl_24, BigDecimal ptc_dbl_25, BigDecimal ptc_dbl_26, BigDecimal ptc_dbl_27, BigDecimal ptc_dbl_28, BigDecimal ptc_dbl_29, BigDecimal ptc_dbl_30, Boolean dropped, Date effectindate, Boolean effectlatest, Date effectoutdate, BigDecimal effectsequence, String flextypeidpath, String classnamekeya4, BigDecimal ida3a4, String classnamekeyb5, BigDecimal ida3b5, String ownerversion, BigDecimal sortingnumber, Date createstampa2, BigDecimal markfordeletea2, Date updatestampa2, BigDecimal branchid, String ownerref, BigDecimal ownerkey, String attributekey, String attributevalue, Date loadercreatetime, Date loaderupdatetime, BigDecimal ida2a2, String datasourcesystem) {
       this.ptc_str_1 = ptc_str_1;
       this.ptc_str_2 = ptc_str_2;
       this.ptc_str_3 = ptc_str_3;
       this.ptc_str_4 = ptc_str_4;
       this.ptc_str_5 = ptc_str_5;
       this.ptc_str_6 = ptc_str_6;
       this.ptc_str_7 = ptc_str_7;
       this.ptc_str_8 = ptc_str_8;
       this.ptc_str_9 = ptc_str_9;
       this.ptc_str_10 = ptc_str_10;
       this.ptc_str_11 = ptc_str_11;
       this.ptc_str_12 = ptc_str_12;
       this.ptc_str_13 = ptc_str_13;
       this.ptc_str_14 = ptc_str_14;
       this.ptc_str_15 = ptc_str_15;
       this.ptc_str_16 = ptc_str_16;
       this.ptc_str_17 = ptc_str_17;
       this.ptc_str_18 = ptc_str_18;
       this.ptc_str_19 = ptc_str_19;
       this.ptc_str_20 = ptc_str_20;
       this.ptc_str_21 = ptc_str_21;
       this.ptc_str_22 = ptc_str_22;
       this.ptc_str_23 = ptc_str_23;
       this.ptc_str_24 = ptc_str_24;
       this.ptc_str_25 = ptc_str_25;
       this.ptc_str_26 = ptc_str_26;
       this.ptc_str_27 = ptc_str_27;
       this.ptc_str_28 = ptc_str_28;
       this.ptc_str_29 = ptc_str_29;
       this.ptc_str_30 = ptc_str_30;
       this.ptc_tms_1 = ptc_tms_1;
       this.ptc_tms_10 = ptc_tms_10;
       this.ptc_tms_2 = ptc_tms_2;
       this.ptc_tms_3 = ptc_tms_3;
       this.ptc_tms_4 = ptc_tms_4;
       this.ptc_tms_5 = ptc_tms_5;
       this.ptc_tms_6 = ptc_tms_6;
       this.ptc_tms_7 = ptc_tms_7;
       this.ptc_tms_8 = ptc_tms_8;
       this.ptc_tms_9 = ptc_tms_9;
       this.ptc_dbl_1 = ptc_dbl_1;
       this.ptc_dbl_2 = ptc_dbl_2;
       this.ptc_dbl_3 = ptc_dbl_3;
       this.ptc_dbl_4 = ptc_dbl_4;
       this.ptc_dbl_5 = ptc_dbl_5;
       this.ptc_dbl_6 = ptc_dbl_6;
       this.ptc_dbl_7 = ptc_dbl_7;
       this.ptc_dbl_8 = ptc_dbl_8;
       this.ptc_dbl_9 = ptc_dbl_9;
       this.ptc_dbl_10 = ptc_dbl_10;
       this.ptc_dbl_11 = ptc_dbl_11;
       this.ptc_dbl_12 = ptc_dbl_12;
       this.ptc_dbl_13 = ptc_dbl_13;
       this.ptc_dbl_14 = ptc_dbl_14;
       this.ptc_dbl_15 = ptc_dbl_15;
       this.ptc_dbl_16 = ptc_dbl_16;
       this.ptc_dbl_17 = ptc_dbl_17;
       this.ptc_dbl_18 = ptc_dbl_18;
       this.ptc_dbl_19 = ptc_dbl_19;
       this.ptc_dbl_20 = ptc_dbl_20;
       this.ptc_dbl_21 = ptc_dbl_21;
       this.ptc_dbl_22 = ptc_dbl_22;
       this.ptc_dbl_23 = ptc_dbl_23;
       this.ptc_dbl_24 = ptc_dbl_24;
       this.ptc_dbl_25 = ptc_dbl_25;
       this.ptc_dbl_26 = ptc_dbl_26;
       this.ptc_dbl_27 = ptc_dbl_27;
       this.ptc_dbl_28 = ptc_dbl_28;
       this.ptc_dbl_29 = ptc_dbl_29;
       this.ptc_dbl_30 = ptc_dbl_30;
       this.dropped = dropped;
       this.effectindate = effectindate;
       this.effectlatest = effectlatest;
       this.effectoutdate = effectoutdate;
       this.effectsequence = effectsequence;
       this.flextypeidpath = flextypeidpath;
       this.classnamekeya4 = classnamekeya4;
       this.ida3a4 = ida3a4;
       this.classnamekeyb5 = classnamekeyb5;
       this.ida3b5 = ida3b5;
       this.ownerversion = ownerversion;
       this.sortingnumber = sortingnumber;
       this.createstampa2 = createstampa2;
       this.markfordeletea2 = markfordeletea2;
       this.updatestampa2 = updatestampa2;
       this.branchid = branchid;
       this.ownerref = ownerref;
       this.ownerkey = ownerkey;
       this.attributekey = attributekey;
       this.attributevalue = attributevalue;
       this.loadercreatetime = loadercreatetime;
       this.loaderupdatetime = loaderupdatetime;
       this.ida2a2 = ida2a2;
       this.datasourcesystem = datasourcesystem;
    }


	public BigDecimal getPrimarykey() {
		return primarykey;
	}


	public void setPrimarykey(BigDecimal primarykey) {
		this.primarykey = primarykey;
	}


	public String getPtc_str_1() {
		return ptc_str_1;
	}


	public void setPtc_str_1(String ptc_str_1) {
		this.ptc_str_1 = ptc_str_1;
	}


	public String getPtc_str_2() {
		return ptc_str_2;
	}


	public void setPtc_str_2(String ptc_str_2) {
		this.ptc_str_2 = ptc_str_2;
	}


	public String getPtc_str_3() {
		return ptc_str_3;
	}


	public void setPtc_str_3(String ptc_str_3) {
		this.ptc_str_3 = ptc_str_3;
	}


	public String getPtc_str_4() {
		return ptc_str_4;
	}


	public void setPtc_str_4(String ptc_str_4) {
		this.ptc_str_4 = ptc_str_4;
	}


	public String getPtc_str_5() {
		return ptc_str_5;
	}


	public void setPtc_str_5(String ptc_str_5) {
		this.ptc_str_5 = ptc_str_5;
	}


	public String getPtc_str_6() {
		return ptc_str_6;
	}


	public void setPtc_str_6(String ptc_str_6) {
		this.ptc_str_6 = ptc_str_6;
	}


	public String getPtc_str_7() {
		return ptc_str_7;
	}


	public void setPtc_str_7(String ptc_str_7) {
		this.ptc_str_7 = ptc_str_7;
	}


	public String getPtc_str_8() {
		return ptc_str_8;
	}


	public void setPtc_str_8(String ptc_str_8) {
		this.ptc_str_8 = ptc_str_8;
	}


	public String getPtc_str_9() {
		return ptc_str_9;
	}


	public void setPtc_str_9(String ptc_str_9) {
		this.ptc_str_9 = ptc_str_9;
	}


	public String getPtc_str_10() {
		return ptc_str_10;
	}


	public void setPtc_str_10(String ptc_str_10) {
		this.ptc_str_10 = ptc_str_10;
	}


	public String getPtc_str_11() {
		return ptc_str_11;
	}


	public void setPtc_str_11(String ptc_str_11) {
		this.ptc_str_11 = ptc_str_11;
	}


	public String getPtc_str_12() {
		return ptc_str_12;
	}


	public void setPtc_str_12(String ptc_str_12) {
		this.ptc_str_12 = ptc_str_12;
	}


	public String getPtc_str_13() {
		return ptc_str_13;
	}


	public void setPtc_str_13(String ptc_str_13) {
		this.ptc_str_13 = ptc_str_13;
	}


	public String getPtc_str_14() {
		return ptc_str_14;
	}


	public void setPtc_str_14(String ptc_str_14) {
		this.ptc_str_14 = ptc_str_14;
	}


	public String getPtc_str_15() {
		return ptc_str_15;
	}


	public void setPtc_str_15(String ptc_str_15) {
		this.ptc_str_15 = ptc_str_15;
	}


	public String getPtc_str_16() {
		return ptc_str_16;
	}


	public void setPtc_str_16(String ptc_str_16) {
		this.ptc_str_16 = ptc_str_16;
	}


	public String getPtc_str_17() {
		return ptc_str_17;
	}


	public void setPtc_str_17(String ptc_str_17) {
		this.ptc_str_17 = ptc_str_17;
	}


	public String getPtc_str_18() {
		return ptc_str_18;
	}


	public void setPtc_str_18(String ptc_str_18) {
		this.ptc_str_18 = ptc_str_18;
	}


	public String getPtc_str_19() {
		return ptc_str_19;
	}


	public void setPtc_str_19(String ptc_str_19) {
		this.ptc_str_19 = ptc_str_19;
	}


	public String getPtc_str_20() {
		return ptc_str_20;
	}


	public void setPtc_str_20(String ptc_str_20) {
		this.ptc_str_20 = ptc_str_20;
	}


	public String getPtc_str_21() {
		return ptc_str_21;
	}


	public void setPtc_str_21(String ptc_str_21) {
		this.ptc_str_21 = ptc_str_21;
	}


	public String getPtc_str_22() {
		return ptc_str_22;
	}


	public void setPtc_str_22(String ptc_str_22) {
		this.ptc_str_22 = ptc_str_22;
	}


	public String getPtc_str_23() {
		return ptc_str_23;
	}


	public void setPtc_str_23(String ptc_str_23) {
		this.ptc_str_23 = ptc_str_23;
	}


	public String getPtc_str_24() {
		return ptc_str_24;
	}


	public void setPtc_str_24(String ptc_str_24) {
		this.ptc_str_24 = ptc_str_24;
	}


	public String getPtc_str_25() {
		return ptc_str_25;
	}


	public void setPtc_str_25(String ptc_str_25) {
		this.ptc_str_25 = ptc_str_25;
	}


	public String getPtc_str_26() {
		return ptc_str_26;
	}


	public void setPtc_str_26(String ptc_str_26) {
		this.ptc_str_26 = ptc_str_26;
	}


	public String getPtc_str_27() {
		return ptc_str_27;
	}


	public void setPtc_str_27(String ptc_str_27) {
		this.ptc_str_27 = ptc_str_27;
	}


	public String getPtc_str_28() {
		return ptc_str_28;
	}


	public void setPtc_str_28(String ptc_str_28) {
		this.ptc_str_28 = ptc_str_28;
	}


	public String getPtc_str_29() {
		return ptc_str_29;
	}


	public void setPtc_str_29(String ptc_str_29) {
		this.ptc_str_29 = ptc_str_29;
	}


	public String getPtc_str_30() {
		return ptc_str_30;
	}


	public void setPtc_str_30(String ptc_str_30) {
		this.ptc_str_30 = ptc_str_30;
	}


	public Date getPtc_tms_1() {
		return ptc_tms_1;
	}


	public void setPtc_tms_1(Date ptc_tms_1) {
		this.ptc_tms_1 = ptc_tms_1;
	}


	public Date getPtc_tms_10() {
		return ptc_tms_10;
	}


	public void setPtc_tms_10(Date ptc_tms_10) {
		this.ptc_tms_10 = ptc_tms_10;
	}


	public Date getPtc_tms_2() {
		return ptc_tms_2;
	}


	public void setPtc_tms_2(Date ptc_tms_2) {
		this.ptc_tms_2 = ptc_tms_2;
	}


	public Date getPtc_tms_3() {
		return ptc_tms_3;
	}


	public void setPtc_tms_3(Date ptc_tms_3) {
		this.ptc_tms_3 = ptc_tms_3;
	}


	public Date getPtc_tms_4() {
		return ptc_tms_4;
	}


	public void setPtc_tms_4(Date ptc_tms_4) {
		this.ptc_tms_4 = ptc_tms_4;
	}


	public Date getPtc_tms_5() {
		return ptc_tms_5;
	}


	public void setPtc_tms_5(Date ptc_tms_5) {
		this.ptc_tms_5 = ptc_tms_5;
	}


	public Date getPtc_tms_6() {
		return ptc_tms_6;
	}


	public void setPtc_tms_6(Date ptc_tms_6) {
		this.ptc_tms_6 = ptc_tms_6;
	}


	public Date getPtc_tms_7() {
		return ptc_tms_7;
	}


	public void setPtc_tms_7(Date ptc_tms_7) {
		this.ptc_tms_7 = ptc_tms_7;
	}


	public Date getPtc_tms_8() {
		return ptc_tms_8;
	}


	public void setPtc_tms_8(Date ptc_tms_8) {
		this.ptc_tms_8 = ptc_tms_8;
	}


	public Date getPtc_tms_9() {
		return ptc_tms_9;
	}


	public void setPtc_tms_9(Date ptc_tms_9) {
		this.ptc_tms_9 = ptc_tms_9;
	}


	public BigDecimal getPtc_dbl_1() {
		return ptc_dbl_1;
	}


	public void setPtc_dbl_1(BigDecimal ptc_dbl_1) {
		this.ptc_dbl_1 = ptc_dbl_1;
	}


	public BigDecimal getPtc_dbl_2() {
		return ptc_dbl_2;
	}


	public void setPtc_dbl_2(BigDecimal ptc_dbl_2) {
		this.ptc_dbl_2 = ptc_dbl_2;
	}


	public BigDecimal getPtc_dbl_3() {
		return ptc_dbl_3;
	}


	public void setPtc_dbl_3(BigDecimal ptc_dbl_3) {
		this.ptc_dbl_3 = ptc_dbl_3;
	}


	public BigDecimal getPtc_dbl_4() {
		return ptc_dbl_4;
	}


	public void setPtc_dbl_4(BigDecimal ptc_dbl_4) {
		this.ptc_dbl_4 = ptc_dbl_4;
	}


	public BigDecimal getPtc_dbl_5() {
		return ptc_dbl_5;
	}


	public void setPtc_dbl_5(BigDecimal ptc_dbl_5) {
		this.ptc_dbl_5 = ptc_dbl_5;
	}


	public BigDecimal getPtc_dbl_6() {
		return ptc_dbl_6;
	}


	public void setPtc_dbl_6(BigDecimal ptc_dbl_6) {
		this.ptc_dbl_6 = ptc_dbl_6;
	}


	public BigDecimal getPtc_dbl_7() {
		return ptc_dbl_7;
	}


	public void setPtc_dbl_7(BigDecimal ptc_dbl_7) {
		this.ptc_dbl_7 = ptc_dbl_7;
	}


	public BigDecimal getPtc_dbl_8() {
		return ptc_dbl_8;
	}


	public void setPtc_dbl_8(BigDecimal ptc_dbl_8) {
		this.ptc_dbl_8 = ptc_dbl_8;
	}


	public BigDecimal getPtc_dbl_9() {
		return ptc_dbl_9;
	}


	public void setPtc_dbl_9(BigDecimal ptc_dbl_9) {
		this.ptc_dbl_9 = ptc_dbl_9;
	}


	public BigDecimal getPtc_dbl_10() {
		return ptc_dbl_10;
	}


	public void setPtc_dbl_10(BigDecimal ptc_dbl_10) {
		this.ptc_dbl_10 = ptc_dbl_10;
	}


	public BigDecimal getPtc_dbl_11() {
		return ptc_dbl_11;
	}


	public void setPtc_dbl_11(BigDecimal ptc_dbl_11) {
		this.ptc_dbl_11 = ptc_dbl_11;
	}


	public BigDecimal getPtc_dbl_12() {
		return ptc_dbl_12;
	}


	public void setPtc_dbl_12(BigDecimal ptc_dbl_12) {
		this.ptc_dbl_12 = ptc_dbl_12;
	}


	public BigDecimal getPtc_dbl_13() {
		return ptc_dbl_13;
	}


	public void setPtc_dbl_13(BigDecimal ptc_dbl_13) {
		this.ptc_dbl_13 = ptc_dbl_13;
	}


	public BigDecimal getPtc_dbl_14() {
		return ptc_dbl_14;
	}


	public void setPtc_dbl_14(BigDecimal ptc_dbl_14) {
		this.ptc_dbl_14 = ptc_dbl_14;
	}


	public BigDecimal getPtc_dbl_15() {
		return ptc_dbl_15;
	}


	public void setPtc_dbl_15(BigDecimal ptc_dbl_15) {
		this.ptc_dbl_15 = ptc_dbl_15;
	}


	public BigDecimal getPtc_dbl_16() {
		return ptc_dbl_16;
	}


	public void setPtc_dbl_16(BigDecimal ptc_dbl_16) {
		this.ptc_dbl_16 = ptc_dbl_16;
	}


	public BigDecimal getPtc_dbl_17() {
		return ptc_dbl_17;
	}


	public void setPtc_dbl_17(BigDecimal ptc_dbl_17) {
		this.ptc_dbl_17 = ptc_dbl_17;
	}


	public BigDecimal getPtc_dbl_18() {
		return ptc_dbl_18;
	}


	public void setPtc_dbl_18(BigDecimal ptc_dbl_18) {
		this.ptc_dbl_18 = ptc_dbl_18;
	}


	public BigDecimal getPtc_dbl_19() {
		return ptc_dbl_19;
	}


	public void setPtc_dbl_19(BigDecimal ptc_dbl_19) {
		this.ptc_dbl_19 = ptc_dbl_19;
	}


	public BigDecimal getPtc_dbl_20() {
		return ptc_dbl_20;
	}


	public void setPtc_dbl_20(BigDecimal ptc_dbl_20) {
		this.ptc_dbl_20 = ptc_dbl_20;
	}


	public BigDecimal getPtc_dbl_21() {
		return ptc_dbl_21;
	}


	public void setPtc_dbl_21(BigDecimal ptc_dbl_21) {
		this.ptc_dbl_21 = ptc_dbl_21;
	}


	public BigDecimal getPtc_dbl_22() {
		return ptc_dbl_22;
	}


	public void setPtc_dbl_22(BigDecimal ptc_dbl_22) {
		this.ptc_dbl_22 = ptc_dbl_22;
	}


	public BigDecimal getPtc_dbl_23() {
		return ptc_dbl_23;
	}


	public void setPtc_dbl_23(BigDecimal ptc_dbl_23) {
		this.ptc_dbl_23 = ptc_dbl_23;
	}


	public BigDecimal getPtc_dbl_24() {
		return ptc_dbl_24;
	}


	public void setPtc_dbl_24(BigDecimal ptc_dbl_24) {
		this.ptc_dbl_24 = ptc_dbl_24;
	}


	public BigDecimal getPtc_dbl_25() {
		return ptc_dbl_25;
	}


	public void setPtc_dbl_25(BigDecimal ptc_dbl_25) {
		this.ptc_dbl_25 = ptc_dbl_25;
	}


	public BigDecimal getPtc_dbl_26() {
		return ptc_dbl_26;
	}


	public void setPtc_dbl_26(BigDecimal ptc_dbl_26) {
		this.ptc_dbl_26 = ptc_dbl_26;
	}


	public BigDecimal getPtc_dbl_27() {
		return ptc_dbl_27;
	}


	public void setPtc_dbl_27(BigDecimal ptc_dbl_27) {
		this.ptc_dbl_27 = ptc_dbl_27;
	}


	public BigDecimal getPtc_dbl_28() {
		return ptc_dbl_28;
	}


	public void setPtc_dbl_28(BigDecimal ptc_dbl_28) {
		this.ptc_dbl_28 = ptc_dbl_28;
	}


	public BigDecimal getPtc_dbl_29() {
		return ptc_dbl_29;
	}


	public void setPtc_dbl_29(BigDecimal ptc_dbl_29) {
		this.ptc_dbl_29 = ptc_dbl_29;
	}


	public BigDecimal getPtc_dbl_30() {
		return ptc_dbl_30;
	}


	public void setPtc_dbl_30(BigDecimal ptc_dbl_30) {
		this.ptc_dbl_30 = ptc_dbl_30;
	}


	public Boolean getDropped() {
		return dropped;
	}


	public void setDropped(Boolean dropped) {
		this.dropped = dropped;
	}


	

	public Boolean getEffectlatest() {
		return effectlatest;
	}


	public void setEffectlatest(Boolean effectlatest) {
		this.effectlatest = effectlatest;
	}



	public Date getEffectindate() {
		return effectindate;
	}


	public void setEffectindate(Date effectindate) {
		this.effectindate = effectindate;
	}


	public Date getEffectoutdate() {
		return effectoutdate;
	}


	public void setEffectoutdate(Date effectoutdate) {
		this.effectoutdate = effectoutdate;
	}


	public BigDecimal getEffectsequence() {
		return effectsequence;
	}


	public void setEffectsequence(BigDecimal effectsequence) {
		this.effectsequence = effectsequence;
	}


	public String getFlextypeidpath() {
		return flextypeidpath;
	}


	public void setFlextypeidpath(String flextypeidpath) {
		this.flextypeidpath = flextypeidpath;
	}


	public String getClassnamekeya4() {
		return classnamekeya4;
	}


	public void setClassnamekeya4(String classnamekeya4) {
		this.classnamekeya4 = classnamekeya4;
	}


	public BigDecimal getIda3a4() {
		return ida3a4;
	}


	public void setIda3a4(BigDecimal ida3a4) {
		this.ida3a4 = ida3a4;
	}


	public String getClassnamekeyb5() {
		return classnamekeyb5;
	}


	public void setClassnamekeyb5(String classnamekeyb5) {
		this.classnamekeyb5 = classnamekeyb5;
	}


	public BigDecimal getIda3b5() {
		return ida3b5;
	}


	public void setIda3b5(BigDecimal ida3b5) {
		this.ida3b5 = ida3b5;
	}


	public String getOwnerversion() {
		return ownerversion;
	}


	public void setOwnerversion(String ownerversion) {
		this.ownerversion = ownerversion;
	}


	

	public Date getCreatestampa2() {
		return createstampa2;
	}


	public void setCreatestampa2(Date createstampa2) {
		this.createstampa2 = createstampa2;
	}


	public BigDecimal getMarkfordeletea2() {
		return markfordeletea2;
	}


	public void setMarkfordeletea2(BigDecimal markfordeletea2) {
		this.markfordeletea2 = markfordeletea2;
	}


	public BigDecimal getBranchid() {
		return branchid;
	}


	public void setBranchid(BigDecimal branchid) {
		this.branchid = branchid;
	}


	public String getOwnerref() {
		return ownerref;
	}


	public void setOwnerref(String ownerref) {
		this.ownerref = ownerref;
	}


	public BigDecimal getOwnerkey() {
		return ownerkey;
	}


	public void setOwnerkey(BigDecimal ownerkey) {
		this.ownerkey = ownerkey;
	}


	
	public Date getLoadercreatetime() {
		return loadercreatetime;
	}


	public void setLoadercreatetime(Date loadercreatetime) {
		this.loadercreatetime = loadercreatetime;
	}


	public BigDecimal getIda2a2() {
		return ida2a2;
	}


	public void setIda2a2(BigDecimal ida2a2) {
		this.ida2a2 = ida2a2;
	}


	public String getDatasourcesystem() {
		return datasourcesystem;
	}


	public void setDatasourcesystem(String datasourcesystem) {
		this.datasourcesystem = datasourcesystem;
	}


	public BigDecimal getSortingnumber() {
		return sortingnumber;
	}


	public void setSortingnumber(BigDecimal sortingnumber) {
		this.sortingnumber = sortingnumber;
	}


	public Date getUpdatestampa2() {
		return updatestampa2;
	}


	public void setUpdatestampa2(Date updatestampa2) {
		this.updatestampa2 = updatestampa2;
	}


	public String getAttributekey() {
		return attributekey;
	}


	public void setAttributekey(String attributekey) {
		this.attributekey = attributekey;
	}


	public String getAttributevalue() {
		return attributevalue;
	}


	public void setAttributevalue(String attributevalue) {
		this.attributevalue = attributevalue;
	}


	public Date getLoaderupdatetime() {
		return loaderupdatetime;
	}


	public void setLoaderupdatetime(Date loaderupdatetime) {
		this.loaderupdatetime = loaderupdatetime;
	}
   
   


}


