
package com.sportmaster.wc.interfaces.webservices.bean;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PlmWS", targetNamespace = "http://www.sportmaster.ru/plmservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PlmWS {


    /**
     * 
     * @param businessSupplierInformationUpdatesRequest
     * @return
     *     returns com.sportmaster.wc.interfaces.webservices.bean.BusinessSupplierInformationUpdatesRequestResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "BusinessSupplierInformationUpdatesRequest")
    @WebResult(name = "BusinessSupplierInformationUpdatesRequestResponse", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "BusinessSupplierInformationUpdatesRequestResponse")
    public BusinessSupplierInformationUpdatesRequestResponse businessSupplierInformationUpdatesRequest(
        @WebParam(name = "BusinessSupplierInformationUpdatesRequest", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "BusinessSupplierInformationUpdatesRequest")
        BusinessSupplierInformationUpdatesRequest businessSupplierInformationUpdatesRequest)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param factoryInformationUpdatesRequest
     * @return
     *     returns com.sportmaster.wc.interfaces.webservices.bean.FactoryInformationUpdatesRequestResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "FactoryInformationUpdatesRequest")
    @WebResult(name = "FactoryInformationUpdatesRequestResponse", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "FactoryInformationUpdatesRequestResponse")
    public FactoryInformationUpdatesRequestResponse factoryInformationUpdatesRequest(
        @WebParam(name = "FactoryInformationUpdatesRequest", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "FactoryInformationUpdatesRequest")
        FactoryInformationUpdatesRequest factoryInformationUpdatesRequest)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param getSimpleBOInformationUpdatesRequest
     * @return
     *     returns com.sportmaster.wc.interfaces.webservices.bean.GetSimpleBOInformationUpdatesRequestResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetSimpleBOInformationUpdatesRequest")
    @WebResult(name = "GetSimpleBOInformationUpdatesRequestResponse", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "GetSimpleBOInformationUpdatesRequestResponse")
    public GetSimpleBOInformationUpdatesRequestResponse getSimpleBOInformationUpdatesRequest(
        @WebParam(name = "GetSimpleBOInformationUpdatesRequest", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "GetSimpleBOInformationUpdatesRequest")
        GetSimpleBOInformationUpdatesRequest getSimpleBOInformationUpdatesRequest)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param getStatusDivisionRequest
     * @return
     *     returns com.sportmaster.wc.interfaces.webservices.bean.GetStatusDivisionRequestResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetStatusDivisionRequest")
    @WebResult(name = "GetStatusDivisionRequestResponse", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "GetStatusDivisionRequestResponse")
    public GetStatusDivisionRequestResponse getStatusDivisionRequest(
        @WebParam(name = "GetStatusDivisionRequest", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "GetStatusDivisionRequest")
        GetStatusDivisionRequest getStatusDivisionRequest)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param packagingInformationUpdatesRequest
     * @return
     *     returns com.sportmaster.wc.interfaces.webservices.bean.PackagingInformationUpdatesRequestResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "PackagingInformationUpdatesRequest")
    @WebResult(name = "PackagingInformationUpdatesRequestResponse", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "PackagingInformationUpdatesRequestResponse")
    public PackagingInformationUpdatesRequestResponse packagingInformationUpdatesRequest(
        @WebParam(name = "PackagingInformationUpdatesRequest", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "PackagingInformationUpdatesRequest")
        PackagingInformationUpdatesRequest packagingInformationUpdatesRequest)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param getStatusSimpleBOInformationRequest
     * @return
     *     returns com.sportmaster.wc.interfaces.webservices.bean.GetStatusSimpleBOInformationRequestResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetStatusSimpleBOInformationRequest")
    @WebResult(name = "GetStatusSimpleBOInformationRequestResponse", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "GetStatusSimpleBOInformationRequestResponse")
    public GetStatusSimpleBOInformationRequestResponse getStatusSimpleBOInformationRequest(
        @WebParam(name = "GetStatusSimpleBOInformationRequest", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "GetStatusSimpleBOInformationRequest")
        GetStatusSimpleBOInformationRequest getStatusSimpleBOInformationRequest)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param shippingInformationUpdatesRequest
     * @return
     *     returns com.sportmaster.wc.interfaces.webservices.bean.ShippingInformationUpdatesRequestResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "ShippingInformationUpdatesRequest")
    @WebResult(name = "ShippingInformationUpdatesRequestResponse", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "ShippingInformationUpdatesRequestResponse")
    public ShippingInformationUpdatesRequestResponse shippingInformationUpdatesRequest(
        @WebParam(name = "ShippingInformationUpdatesRequest", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "ShippingInformationUpdatesRequest")
        ShippingInformationUpdatesRequest shippingInformationUpdatesRequest)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param materialInformationUpdatesRequest
     * @return
     *     returns com.sportmaster.wc.interfaces.webservices.bean.MaterialInformationUpdatesRequestResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "MaterialInformationUpdatesRequest")
    @WebResult(name = "MaterialInformationUpdatesRequestResponse", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "MaterialInformationUpdatesRequestResponse")
    public MaterialInformationUpdatesRequestResponse materialInformationUpdatesRequest(
        @WebParam(name = "MaterialInformationUpdatesRequest", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "MaterialInformationUpdatesRequest")
        MaterialInformationUpdatesRequest materialInformationUpdatesRequest)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param decorationInformationUpdatesRequest
     * @return
     *     returns com.sportmaster.wc.interfaces.webservices.bean.DecorationInformationUpdatesRequestResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "DecorationInformationUpdatesRequest")
    @WebResult(name = "DecorationInformationUpdatesRequestResponse", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "DecorationInformationUpdatesRequestResponse")
    public DecorationInformationUpdatesRequestResponse decorationInformationUpdatesRequest(
        @WebParam(name = "DecorationInformationUpdatesRequest", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "DecorationInformationUpdatesRequest")
        DecorationInformationUpdatesRequest decorationInformationUpdatesRequest)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param fabricMaterialInformationUpdatesRequest
     * @return
     *     returns com.sportmaster.wc.interfaces.webservices.bean.FabricMaterialInformationUpdatesRequestResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "FabricMaterialInformationUpdatesRequest")
    @WebResult(name = "FabricMaterialInformationUpdatesRequestResponse", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "FabricMaterialInformationUpdatesRequestResponse")
    public FabricMaterialInformationUpdatesRequestResponse fabricMaterialInformationUpdatesRequest(
        @WebParam(name = "FabricMaterialInformationUpdatesRequest", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "FabricMaterialInformationUpdatesRequest")
        FabricMaterialInformationUpdatesRequest fabricMaterialInformationUpdatesRequest)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param getDivisionUpdatesRequest
     * @return
     *     returns com.sportmaster.wc.interfaces.webservices.bean.GetDivisionUpdatesRequestResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "GetDivisionUpdatesRequest")
    @WebResult(name = "GetDivisionUpdatesRequestResponse", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "GetDivisionUpdatesRequestResponse")
    public GetDivisionUpdatesRequestResponse getDivisionUpdatesRequest(
        @WebParam(name = "GetDivisionUpdatesRequest", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "GetDivisionUpdatesRequest")
        GetDivisionUpdatesRequest getDivisionUpdatesRequest)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param trimsInformationUpdatesRequest
     * @return
     *     returns com.sportmaster.wc.interfaces.webservices.bean.TrimsInformationUpdatesRequestResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "TrimsInformationUpdatesRequest")
    @WebResult(name = "TrimsInformationUpdatesRequestResponse", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "TrimsInformationUpdatesRequestResponse")
    public TrimsInformationUpdatesRequestResponse trimsInformationUpdatesRequest(
        @WebParam(name = "TrimsInformationUpdatesRequest", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "TrimsInformationUpdatesRequest")
        TrimsInformationUpdatesRequest trimsInformationUpdatesRequest)
        throws SQLException_Exception
    ;

    /**
     * 
     * @param materialSupplierInformationUpdatesRequest
     * @return
     *     returns com.sportmaster.wc.interfaces.webservices.bean.MaterialSupplierInformationUpdatesRequestResponse
     * @throws SQLException_Exception
     */
    @WebMethod(operationName = "MaterialSupplierInformationUpdatesRequest")
    @WebResult(name = "MaterialSupplierInformationUpdatesRequestResponse", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "MaterialSupplierInformationUpdatesRequestResponse")
    public MaterialSupplierInformationUpdatesRequestResponse materialSupplierInformationUpdatesRequest(
        @WebParam(name = "MaterialSupplierInformationUpdatesRequest", targetNamespace = "http://www.sportmaster.ru/plmservice", partName = "MaterialSupplierInformationUpdatesRequest")
        MaterialSupplierInformationUpdatesRequest materialSupplierInformationUpdatesRequest)
        throws SQLException_Exception
    ;

}
